Repository xcat2/xcat-core, pull requests merged in 2018-09, with the labels that each got.

#5586 move test cases of kit from ubuntu to rhels7 test case bundle
  xCAT-test/autotest/bundle/rhels7.4_ppc64.bundle
  xCAT-test/autotest/bundle/rhels7.4_ppc64le.bundle
  xCAT-test/autotest/bundle/rhels7.4_x86_64.bundle
  xCAT-test/autotest/bundle/ubuntu14.04.3_ppc64le.bundle
  xCAT-test/autotest/bundle/ubuntu14.04.3_x86_64.bundle
  xCAT-test/autotest/bundle/ubuntu14.04.4_ppc64le.bundle
  xCAT-test/autotest/bundle/ubuntu14.04.4_x86_64.bundle
  xCAT-test/autotest/bundle/ubuntu16.04.1_ppc64le.bundle
  xCAT-test/autotest/bundle/ubuntu16.04.1_x86_64.bundle
  xCAT-test/autotest/bundle/ubuntu16.04_ppc64le.bundle
  xCAT-test/autotest/bundle/ubuntu16.04_x86_64.bundle
Labels: component:test

#5589 Add EPEL repo for installing docker-ce in testcase
  xCAT-test/autotest/testcase/performance/simulatorctl.sh
Labels: sprint1

#5587 support nics type Omnipath in confignetwork
  xCAT/postscripts/confignetwork
Labels: component:network

#5592 Modify test case buildkit_v to support rhels
  xCAT-test/autotest/testcase/buildkit/cases0
Labels: component:kit, component:test, sprint1

#5572 Add /etc/gshadow for the syncfile MERGE clause
  perl-xCAT/xCAT/CFMUtils.pm
  perl-xCAT/xCAT/DSHCLI.pm
Labels: component:postscripts, type:support

#5601 fix issue 5598, return 1 when invalid id for reventlog resolved
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_eventlog.py
Labels: component:openbmc

#5583 add HA test cases for redhat
  xCAT-test/autotest/linux.conf.template
  xCAT-test/autotest/testcase/HA/case0
  xCAT-test/autotest/testcase/HA/cfghamn
  xCAT-test/autotest/testcase/HA/check_node_state
Labels: component:test

#5608 reuse MN_basic.bundle as CI test scope to fast test
  travis.pl
Labels: component:CI, component:test

#5602 Clarify doc for REST API over http
  docs/source/advanced/networks/infiniband/network_configuration.rst
  docs/source/advanced/restapi/restapi_setup/restapi_setup.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/install_new_kernel.rst
Labels: component:restapi, type:documentation

#5613 Fix bug #5612 of xcattest
  xCAT-test/xcattest
Labels: component:test, sprint1

#5607 fix issue 5604, delete extra / of rootimgdir
  xCAT-server/share/xcat/ib/scripts/Mellanox/mlnxofed_ib_install.v2
Labels: component:infiniband

#5569 retry in rpower reset when get 'Connection aborted' [ DO NOT MERGE ]
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_power.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
Labels: component:openbmc

#5619 fix issue 5617, show existed node info when bmcdiscover -z
  xCAT-server/lib/xcat/plugins/bmcdiscover.pm
Labels: component:hw_control

#5632 xcat-inventory diff cases
  xCAT-test/autotest/testcase/xcat-inventory/cases.diff
  xCAT-test/autotest/testcase/xcat-inventory/diff/change_name.sh
  xCAT-test/autotest/testcase/xcat-inventory/diff/diff_files.result
  xCAT-test/autotest/testcase/xcat-inventory/diff/diff_source.result
  xCAT-test/autotest/testcase/xcat-inventory/diff/xcat-inventory_diff_file1.json
  xCAT-test/autotest/testcase/xcat-inventory/diff/xcat-inventory_diff_file2.json
Labels: component:automation

#5636 fix no space left on sles12.3 servicenode
  xCAT-server/share/xcat/install/sles/service.sles12.tmpl
Labels: component:os_provision

#5628 modify openbmc python installation doc
  docs/source/references/coral/cluster_mgmt/scalability/python/install/rpm.rst
Labels: type:documentation

#5585 Remove 2 PR template under .github/PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE/fix_issue_template.md
  .github/PULL_REQUEST_TEMPLATE/function_template.md
Labels: type:usability

#5648 fix issue genimage failure might cause /proc umounted #5640
  xCAT-server/share/xcat/netboot/rh/genimage
Labels: type:bug

#5638 Update RHEV docs
  docs/source/guides/admin-guides/manage_clusters/ppc64le/virtual_machines/RHEVHypervisor.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/virtual_machines/hypervisorKVM.rst
Labels: type:documentation

#5651 Fix issue 5649: makedhcp misleading error message
  xCAT-server/lib/xcat/plugins/dhcp.pm
Labels: component:dhcp

#5639 fix issue 5633, enhance check tftp service
  xCAT-probe/lib/perl/probe_utils.pm
  xCAT-probe/subcmds/xcatmn
Labels: component:xcatprobe

#5670 Get group name from lsdef command
  xCAT-client/share/xcat/tools/groupfiles4dsh
Labels: component:obj_db_cmds

#5671 add label for xcat-inventory test cases
  xCAT-test/autotest/testcase/xcat-inventory/cases.common
  xCAT-test/autotest/testcase/xcat-inventory/cases.network
  xCAT-test/autotest/testcase/xcat-inventory/cases.node
  xCAT-test/autotest/testcase/xcat-inventory/cases.osimage
  xCAT-test/autotest/testcase/xcat-inventory/cases.osimage.import_from_osimage_dir
  xCAT-test/autotest/testcase/xcat-inventory/cases.osimage.validation
  xCAT-test/autotest/testcase/xcat-inventory/cases.passwd
  xCAT-test/autotest/testcase/xcat-inventory/cases.route
  xCAT-test/autotest/testcase/xcat-inventory/cases.site
  xCAT-test/autotest/testcase/xcat-inventory/cases.site.validation
Labels: component:test

#5654 Doc enhancements to localdisk instructions
  docs/source/advanced/hierarchy/provision/diskless_sn.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/enable_localdisk.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/localdisk.rst
Labels: type:documentation
