Repository xcat2/xcat-core, pull requests merged in 2018-02, with the labels that each got.

#4815 Allow choosing individual openbmc commands to use Python
  xCAT-server/lib/perl/xCAT/OPENBMC.pm
  xCAT-server/lib/xcat/plugins/openbmc.pm
  xCAT-server/lib/xcat/plugins/openbmc2.pm
Labels: component:openbmc

#4821 add libnss_dns to xcat-genesis-base
  xCAT-genesis-builder/buildrpm
  xCAT-genesis-builder/install
  xCAT-genesis-builder/xCAT-genesis-builder.spec
Labels: component:discovery

#4823 Better handling multiple dots in copycds name
  xCAT-server/lib/perl/xCAT/SvrUtils.pm
Labels: component:obj_db_cmds

#4825 Add milestone and labels checking in the CI test system
  travis.pl
Labels: component:CI

#4801 Support user defined password from pdu table
  xCAT-server/lib/xcat/plugins/pdu.pm
  xCAT-server/lib/xcat/plugins/switchdiscover.pm
Labels: component:coral, component:hw_control, type:support

#4828 rinv,rpower,rvitals,rflash - Display OpenBMC usage to simplify help output
  perl-xCAT/xCAT/Usage.pm
Labels: type:usability

#4836 Build xCAT-openbmc-py, improve message when debugging missing dependencies in the python agent
  buildcore.sh
  makerpm-python
  xCAT-openbmc-py/lib/python/agent/xcatagent/base.py
  xCAT-server/lib/perl/xCAT/OPENBMC.pm
  xCAT-server/lib/xcat/plugins/openbmc2.pm
Labels: component:openbmc, type:usability

#4834 Get xCAT MASTER from dhcpclient lease file for configinterface postscripts
  xCAT/postscripts/configinterface
Labels: component:dhcp, component:postscripts, type:support

#4827 rspconfig in python to get network information
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_bmcconfig.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
  xCAT-openbmc-py/lib/python/agent/xcatagent/openbmc.py
Labels: sprint2

#4838 rspconfig dump in python
  xCAT-openbmc-py/lib/python/agent/common/rest.py
  xCAT-openbmc-py/lib/python/agent/hwctl/bmcconfig.py
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_bmcconfig.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
  xCAT-openbmc-py/lib/python/agent/xcatagent/openbmc.py
Labels: component:openbmc

#4846 enhance kdump doc crashkernelsize section
  docs/source/guides/admin-guides/manage_clusters/common/deployment/enable_kdump.rst
Labels: type:documentation

#4850 Fix bug for test case rspconfig_set_hostname_equal_star_with_bmc_is_hostname
  xCAT-test/autotest/testcase/reventlog/cases0
  xCAT-test/autotest/testcase/rspconfig/cases0
Labels: component:test

#4835 Initial pass for Python reventlog
  xCAT-openbmc-py/lib/python/agent/hwctl/eventlog.py
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_eventlog.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
  xCAT-openbmc-py/lib/python/agent/xcatagent/openbmc.py
  xCAT-openbmc-py/lib/python/agent/xcatagent/server.py
  xCAT-server/lib/xcat/plugins/openbmc2.pm
Labels: component:openbmc

#4839 fix not set domain in site table will cause dhcp service failed to start
  xCAT-server/lib/xcat/plugins/dhcp.pm
Labels: component:dhcp

#4862 Fix the git short commit id to 7-byte long
  build-ubunturepo
  buildcore.sh
Labels: component:packaging, sprint2

#4857 Remove "dynamic" checking in the doxcat scripts
  xCAT-genesis-scripts/usr/bin/doxcat
Labels: component:discovery

#4816 Add makegocons -q in the man page
  docs/source/guides/admin-guides/references/man8/makegocons.8.rst
  xCAT-client/pods/man8/makegocons.8.pod
Labels: component:goconserver, type:documentation
