Repository xcat2/xcat-core, pull requests merged in 2018-08, with the labels that each got.

#5449 Avoid use command route in configeth, since it is obsoleted
  xCAT/postscripts/configeth
Labels: component:network, sprint2

#5456 Suppress the `index.attr, No such file or directory' error message from openssl
  xCAT-server/share/xcat/scripts/setup-dockerhost-cert.sh
  xCAT-server/share/xcat/scripts/setup-xcat-ca.sh
Labels: component:security, sprint2

#5457 change file system partition type to xfs for sles12sp3
  xCAT-server/share/xcat/install/scripts/pre.sles
Labels: component:os_provision

#5461 check BMC state after BMCreboot in rflash -d
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: sprint2

#5464 Fix minor configeth problem on Ubuntu 18.04
  xCAT/postscripts/configeth
Labels: component:network, sprint2

#5450 Revise go_xcat_noinput test case, by install package gpg on Ubuntu compute node
  xCAT-test/autotest/testcase/go-xcat/case1
Labels: component:go-xcat, sprint2

#5460 Avoid use command ifconfig in test case psh_i
  xCAT-test/autotest/testcase/psh/cases0
Labels: sprint2

#5452 Allow any command for runcmd= option
  docs/source/guides/admin-guides/references/man8/nodeset.8.rst
  docs/source/guides/admin-guides/references/man8/rinstall.8.rst
  xCAT-client/pods/man8/nodeset.8.pod
  xCAT-client/pods/man8/rinstall.8.pod
  xCAT-server/lib/xcat/plugins/rinstall.pm
Labels: component:os_provision

#5467 Fix psh_i test case on Ubuntu 18.04
  xCAT-test/autotest/testcase/psh/cases0
Labels: sprint2

#5463 specify build pkg dir when build rpm/deb
  build-ubunturepo
  buildcore.sh
Labels: component:packaging

#5341 Early support for RHEL 8 Alpha Base OS diskful installation
  xCAT-server/share/xcat/install/rh/compute.rhels8.pkglist
  xCAT-server/share/xcat/install/rh/compute.rhels8.tmpl
  xCAT-server/share/xcat/install/scripts/post.rhels8
  xCAT-server/share/xcat/install/scripts/post.xcat.ng
  xCAT-server/share/xcat/install/scripts/pre.rhels8
Labels: component:os_provision, sprint1

#5468 Add more debug information to test case psh_i for issue 5466
  xCAT-test/autotest/testcase/psh/cases0
Labels: component:test

#5424 enhancement on build xcat-core script to support output to directory
  build-ubunturepo
  buildcore.sh
Labels: sprint1

#5471 code error cause rpm package is not signed
  buildcore.sh
Labels: component:packaging

#5473 put the tarball directly under DEST directory when building xcat-core
  build-ubunturepo
  buildcore.sh
Labels: component:packaging

#5469 fix /etc/hosts empty in sles12sp3 diskful installation
  xCAT-server/share/xcat/install/sles/compute.sles12.tmpl
  xCAT-server/share/xcat/install/sles/service.sles12.tmpl
Labels: sprint2

#5474 set buildall to default when build ubuntu
  build-ubunturepo
Labels: component:packaging

#5475 Fix test case go_xcat_noinput. Ignore the exit code of gpg installation
  xCAT-test/autotest/testcase/go-xcat/case1
Labels: sprint2

#5482 skip discovery if the static dhcp lease of switch already exists
  xCAT/postscripts/cumulusztp
Labels: cumulus, priority:high

#5485 Use xCAT Automatic Signing Key, 5619700D to do the signing
  buildcore.sh
Labels: component:packaging

#5487 fix typo in informational message
  xCAT-probe/subcmds/discovery
  xCAT-server/lib/xcat/plugins/nodediscover.pm
Labels: type:documentation

#5447 Stop rinstall processing if runimage is invalid
  xCAT-server/lib/xcat/plugins/destiny.pm
  xCAT-server/lib/xcat/plugins/rinstall.pm
Labels: component:os_provision

#5504 fix issue 5499: rflash option needed to update PNOR or BMC individually for P9 OpenPower servers
  xCAT-server/lib/xcat/plugins/ipmi.pm
Labels: component:hw_control

#5418 Using label to enhance CI test
  travis.pl
  xCAT-test/autotest/testcase/makedhcp/cases0
  xCAT-test/autotest/testcase/makedns/cases0
  xCAT-test/autotest/testcase/makehosts/cases0
  xCAT-test/autotest/testcase/mkdef/cases0
  xCAT-test/autotest/testcase/xcatconfig/case0
  xCAT-test/autotest/testcase/xcatd/case0
  xCAT-test/autotest/testcase/xcatstanzafile/cases0
Labels: component:CI, component:test, sprint2

#5477 Update xCAT document for Ubuntu 18.04
  docs/source/guides/admin-guides/manage_clusters/common/deployment/additionalpkg/ubuntu_os_other_pkg.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/create_img.rst
  docs/source/guides/install-guides/apt/configure_xcat.rst
  docs/source/guides/install-guides/apt/prepare_mgmt_node.rst
  docs/source/overview/xcat2_release.rst
Labels: sprint2, type:documentation

#5515 fix when xcatdebugmode=1, non shell (/bin/sh) postscripts will not show output back on MN #5510
  xCAT/postscripts/xcatdsklspost
Labels: component:os_provision

#5519 Fix issue 5518: perl-xCAT/xCAT/MacMap.pm on ubuntu18.4 and rhels6.10
  perl-xCAT/xCAT/MacMap.pm
Labels: component:discovery

#5524 Support multiple syncfile list for packimage
  xCAT-server/lib/xcat/plugins/packimage.pm
  xCAT-server/lib/xcat/plugins/statelite.pm
Labels: component:file_sync, component:packaging

#5523 Add --noupdateinitrd option to rinstall
  docs/source/guides/admin-guides/references/man8/nodeset.8.rst
  docs/source/guides/admin-guides/references/man8/rinstall.8.rst
  xCAT-client/pods/man8/nodeset.8.pod
  xCAT-client/pods/man8/rinstall.8.pod
  xCAT-server/lib/xcat/plugins/rinstall.pm
Labels: component:os_provision

#5530 To replace PR 5130: Update version_control_inventory.rst
  docs/source/advanced/xcat-inventory/version_control_inventory.rst
Labels: type:documentation

#5359 Lock rflash operation
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:hw_control, component:openbmc, test:testcase_requested

#5483 Support rspconfig sshcfg command for cumulus switch
  xCAT-server/lib/xcat/plugins/onie.pm
Labels: component:coral, component:discovery, component:hw_control

#5531 Replace 5478 to fix issue 5476
  xCAT-server/lib/xcat/plugins/geninitrd.pm
Labels: component:os_provision

#5470 SuSE Linux 15 support
  xCAT-server/lib/xcat/plugins/anaconda.pm
  xCAT-server/lib/xcat/plugins/sles.pm
  xCAT-server/share/xcat/install/scripts/pre.sle15
  xCAT-server/share/xcat/install/sles/compute.sle15.pkglist
  xCAT-server/share/xcat/install/sles/compute.sle15.tmpl
  xCAT/postscripts/remoteshell
Labels: component:os_provision, type:feature

#5542 To fix issue that lose activation success log
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:openbmc, sprint2

#5544 Modify release information for 2.14.3 release
  docs/source/conf.py
  docs/source/overview/xcat2_release.rst
Labels: component:automation

#5535 Enhancement for using site cache in plugin
  perl-xCAT/xCAT/Client.pm
  perl-xCAT/xCAT/Table.pm
  perl-xCAT/xCAT/TableUtils.pm
  xCAT-server/sbin/xcatd
Labels: component:database

#5557 capture retrieve_fd fatal error, log the underlie message
  xCAT-server/lib/xcat/plugins/ipmi.pm
Labels: component:hw_control

#5559 fix issue 5548, if ip source is dhcp will remind that could not set ntpservers
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_bmcconfig.py
  xCAT-server/lib/xcat/plugins/ipmi.pm
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:openbmc

#5549 Change options from V|Verbose to V|verbose
  docs/source/guides/admin-guides/references/man1/chzone.1.rst
  docs/source/guides/admin-guides/references/man1/mkzone.1.rst
  docs/source/guides/admin-guides/references/man1/rmzone.1.rst
  docs/source/guides/admin-guides/references/man1/sinv.1.rst
  perl-xCAT/xCAT/PPClog.pm
  perl-xCAT/xCAT/SINV.pm
  xCAT-client/pods/man1/chzone.1.pod
  xCAT-client/pods/man1/mkzone.1.pod
  xCAT-client/pods/man1/rmzone.1.pod
  xCAT-client/pods/man1/sinv.1.pod
  xCAT-server/lib/xcat/plugins/docker.pm
  xCAT-server/lib/xcat/plugins/hpblade.pm
  xCAT-server/lib/xcat/plugins/lsslp.pm
  xCAT-server/lib/xcat/plugins/makentp.pm
  xCAT-server/lib/xcat/plugins/rescanplugins.pm
  xCAT-server/lib/xcat/plugins/xCATWorld.pm
  xCAT-server/lib/xcat/plugins/zone.pm
Labels: component:parallel_cmds

#5566 enhance statelite persistent dir mount options for rh7.6
  xCAT-server/share/xcat/netboot/rh/dracut_033/xcat-prepivot.sh
Labels: component:os_provision

#5567 Provide RHEL7->RHEL8 diskless support
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.ppc64.exlist
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.ppc64.pkglist
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.ppc64.postinstall
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.ppc64le.exlist
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.ppc64le.pkglist
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.ppc64le.postinstall
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.x86_64.exlist
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.x86_64.pkglist
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.x86_64.postinstall
  xCAT-server/share/xcat/netboot/rh/dracut_047/check
  xCAT-server/share/xcat/netboot/rh/dracut_047/install.netboot
  xCAT-server/share/xcat/netboot/rh/dracut_047/install.statelite
  xCAT-server/share/xcat/netboot/rh/dracut_047/installkernel
  xCAT-server/share/xcat/netboot/rh/dracut_047/patch/syslog/module-setup.sh
  xCAT-server/share/xcat/netboot/rh/dracut_047/patch/syslog/rsyslogd-start.sh
  xCAT-server/share/xcat/netboot/rh/dracut_047/patch/syslog/syslog-genrules.sh
  xCAT-server/share/xcat/netboot/rh/dracut_047/xcat-cmdline.sh
  xCAT-server/share/xcat/netboot/rh/dracut_047/xcat-premount.sh
  xCAT-server/share/xcat/netboot/rh/dracut_047/xcat-prepivot.sh
  xCAT-server/share/xcat/netboot/rh/dracut_047/xcatroot
  xCAT-server/share/xcat/netboot/rh/genimage
Labels: sprint2

#5580 fix issue #105 in xcat-inventory,
  xCAT-server/lib/perl/xCAT/Postage.pm
Labels: type:bug

#5570 support encode hyphens in xcatlib.sh
  xCAT/postscripts/xcatlib.sh
Labels: sprint1

#5568 Only update switch/port information for mtms based discovery
  xCAT-server/lib/xcat/plugins/nodediscover.pm
Labels: component:discovery
