Repository xcat2/xcat-core, pull requests merged in 2018-11, with the labels that each got.

#5760 A more real world partitioning scheme for RHEL8
  xCAT-server/share/xcat/install/scripts/pre.rhels8
Labels: component:os_provision

#5767 missing /etc/rsyslog.d/ from litefile table
  docs/source/guides/admin-guides/manage_clusters/ppc64le/statelite/config_statelite.rst
Labels: sprint2

#5771 add sys log for redhat statelite
  xCAT-server/share/xcat/netboot/rh/dracut/xcat-premount.sh
  xCAT-server/share/xcat/netboot/rh/dracut_033/xcat-premount.sh
  xCAT-server/share/xcat/netboot/rh/dracut_033/xcat-prepivot.sh
  xCAT-server/share/xcat/netboot/rh/dracut_033/xcatroot
  xCAT-server/share/xcat/netboot/rh/dracut_047/xcat-premount.sh
  xCAT-server/share/xcat/netboot/rh/dracut_047/xcat-prepivot.sh
  xCAT-server/share/xcat/netboot/rh/dracut_047/xcatroot
  xCAT-server/share/xcat/netboot/sles/dracut_033/xcat-premount.sh
  xCAT/postscripts/xcatdsklspost
  xCAT/postscripts/xcatpostinit1.netboot
Labels: sprint2

#5781 fix 5733 genimage in ubuntu16.04.5 failure
  xCAT-server/share/xcat/netboot/ubuntu/compute.ubuntu16.04.pkglist
  xCAT-server/share/xcat/netboot/ubuntu/compute.ubuntu16.04.ppc64el.pkglist
  xCAT-server/share/xcat/netboot/ubuntu/compute.ubuntu16.04.x86_64.pkglist
Labels: component:os_provision

#5783 fix5209 nodeset cannot find pxelinux.0
  xCAT-server/lib/xcat/plugins/mknb.pm
  xCAT-server/lib/xcat/plugins/pxe.pm
Labels: sprint2

#5772 Patch sles_migration test cases. Workaround for github issue #5503
  xCAT-test/autotest/testcase/migration/sles_migration
Labels: sprint2

#5786 Modify configinterface postscripts to handle the MASTER IP address
  xCAT/postscripts/configinterface
Labels: component:postscripts, component:updatenode

#5801 fix 5800 nicextraparams does not overwrite existed ifcfg attribute
  xCAT/postscripts/nicutils.sh
  xCAT/postscripts/xcatlib.sh
Labels: component:network

#5805 add log tag for postscripts
  xCAT/postscripts/addsiteyum
  xCAT/postscripts/configbond
  xCAT/postscripts/configib
  xCAT/postscripts/confignics
  xCAT/postscripts/enablecapi
  xCAT/postscripts/mkhyperv
  xCAT/postscripts/mkresolvconf
  xCAT/postscripts/mountinstall
  xCAT/postscripts/odbcsetup
  xCAT/postscripts/redirectps
  xCAT/postscripts/routeop
  xCAT/postscripts/serialconsole
  xCAT/postscripts/setbootfromdisk
  xCAT/postscripts/setbootfromnet
  xCAT/postscripts/setiscsiparms.awk
  xCAT/postscripts/setupLDAP
  xCAT/postscripts/setupesx
  xCAT/postscripts/setupnfsv4replication
  xCAT/postscripts/setupntp
  xCAT/postscripts/setupntp.traditional
  xCAT/postscripts/setuppostbootscripts
  xCAT/postscripts/setupscratch
  xCAT/postscripts/sudoer
  xCAT/postscripts/umountpost
  xCAT/postscripts/unlocktftpdir.awk
  xCAT/postscripts/xcatclient
  xCAT/postscripts/xcatpostinit
  xCAT/postscripts/xcatserver
Labels: sprint2

#5809 confignics find wrong network for nic when mask is empty
  xCAT/postscripts/confignics
Labels: component:network, sprint2

#5808 when no ipmitool-xcat tool, report error before go ahead the real discovery
  xCAT-server/lib/xcat/plugins/bmcdiscover.pm
Labels: sprint2

#5758 Use postscript file efibootmgr to check http service instead of syslog
  xCAT-probe/lib/perl/probe_utils.pm
Labels: component:xcatprobe

#5792 do task395, update xcat-inventory cases for code design change -- fix the output change
  xCAT-test/autotest/testcase/xcat-inventory/cases.environment
  xCAT-test/autotest/testcase/xcat-inventory/cases.nics
  xCAT-test/autotest/testcase/xcat-inventory/cases.osimage
Labels: sprint2

#5815 do task 397,fix xcat-inventory cases for ubuntu command not found
  xCAT-test/autotest/testcase/xcat-inventory/cases.node
  xCAT-test/autotest/testcase/xcat-inventory/cases.osimage
  xCAT-test/autotest/testcase/xcat-inventory/cases.site
Labels: component:test

#5821 fix CI issue
  travis.pl
Labels: component:CI

#5824 Fix shabang for some old scripts
  xCAT-server/share/xcat/scripts/setup-dockerhost-cert.sh
  xCAT-server/share/xcat/scripts/setup-local-client.sh
Labels: sprint2

#5823 upgrade to travis xenial env
  .travis.yml
  travis.pl
  xCAT-server/lib/xcat/monitoring/snmpmon.pm
  xCAT-test/autotest/bundle/MN_basic.bundle
  xCAT-test/autotest/testcase/makedhcp/cases0
Labels: sprint2

#5692 enhance rspconfig ntpservers case
  xCAT-test/autotest/testcase/rspconfig/rspconfig_ntp.sh
Labels: component:test

#5826 Fix issue 5721: xCAT-client rpm seems to depend on xCAT-server
  perl-xCAT/xCAT/FSPpower.pm
  perl-xCAT/xCAT/PPCboot.pm
  perl-xCAT/xCAT/PPCpower.pm
Labels: component:packaging

#5832 Fix the gpg key import problem on SLES
  xCAT-test/autotest/testcase/migration/sles_migration
Labels: sprint2

#5753 Minor go-xcat updates
  xCAT-server/share/xcat/tools/go-xcat
Labels: component:go-xcat, sprint2

#5827 [go-xcat] Force use POSIX locale when do rpm query
  xCAT-server/share/xcat/tools/go-xcat
Labels: component:go-xcat, sprint2

#5829 fix issue 5719, make output of commands against openbmc same
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_inventory.py
  xCAT-server/lib/xcat/plugins/openbmc.pm
  xCAT-server/lib/xcat/plugins/openbmc2.pm
  xCAT-test/autotest/testcase/UT_openbmc/supported_commands_case0
  xCAT-test/autotest/testcase/rspconfig/cases1
  xCAT-test/autotest/testcase/rspconfig/rspconfig.sh
Labels: component:openbmc

#5831 refine tag prefix xcat.deployment for sles/ubuntu provision
  xCAT-server/share/xcat/netboot/sles/dracut_033/install.statelite
  xCAT-server/share/xcat/netboot/sles/dracut_033/xcat-premount.sh
  xCAT-server/share/xcat/netboot/sles/dracut_033/xcat-prepivot.sh
  xCAT-server/share/xcat/netboot/sles/dracut_033/xcatroot
  xCAT-server/share/xcat/netboot/ubuntu/genimage
  xCAT/postscripts/xcatpostinit
  xCAT/postscripts/xcatpostinit1.service.yast2
Labels: sprint2

#5811 add http port change case, do task 339
  xCAT-test/autotest/testcase/httpport/cases0
  xCAT-test/autotest/testcase/httpport/change_http_port.sh
Labels: component:test

#5834 EXECUTEALWAYS will only execute syncfile in the syncfile list
  perl-xCAT/xCAT/DSHCLI.pm
Labels: component:file_sync, component:postscripts, component:updatenode

#5838 add syslog for pre script
  xCAT-server/share/xcat/install/scripts/post.xcat
  xCAT-server/share/xcat/install/scripts/pre.rh
  xCAT-server/share/xcat/install/scripts/pre.rh.rhels7
  xCAT-server/share/xcat/install/scripts/pre.rhels8
  xCAT-server/share/xcat/install/scripts/pre.sle15
  xCAT-server/share/xcat/install/scripts/pre.sles
  xCAT-server/share/xcat/install/scripts/pre.ubuntu
  xCAT-server/share/xcat/install/scripts/pre.ubuntu.ppc64
Labels: component:os_provision

#5844 update arch for x86_64
  xCAT-test/autotest/testcase/go_xcat/case0
  xCAT-test/autotest/testcase/go_xcat/case1
  xCAT-test/autotest/testcase/go_xcat/case2
  xCAT-test/autotest/testcase/go_xcat/case4
  xCAT-test/autotest/testcase/nodestat/cases0
  xCAT-test/autotest/testcase/snpool/not_set_xcatmaster_in_sn_pool_tftp_sync_mode
Labels: component:test

#5803 Additional info display for rspconfig
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_bmcconfig.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
Labels: component:openbmc

#5846 Fix issue 5150: tabch and tabdump commands can not deal with invalid attribute names
  perl-xCAT/xCAT/Table.pm
  xCAT-server/lib/xcat/plugins/tabutils.pm
Labels: component:obj_db_cmds

#5787 Determine NumberNodes in the command.log by the command requests
  xCAT-server/lib/xcat/plugins/DBobjectdefs.pm
Labels: component:obj_db_cmds, component:parallel_cmds
