Repository xcat2/xcat-core, pull requests merged in 2018-07, with the labels that each got.

#5353 Add labels for test cases which test DB operation command
  xCAT-test/autotest/testcase/chdef/cases0
  xCAT-test/autotest/testcase/chtab/cases0
  xCAT-test/autotest/testcase/dumpxCATdb/cases0
  xCAT-test/autotest/testcase/gettab/cases0
  xCAT-test/autotest/testcase/lsdef/cases0
  xCAT-test/autotest/testcase/mkdef/cases0
  xCAT-test/autotest/testcase/mkdef/cases1
  xCAT-test/autotest/testcase/nodeadd/cases0
  xCAT-test/autotest/testcase/nodech/cases0
  xCAT-test/autotest/testcase/nodegrpch/cases0
  xCAT-test/autotest/testcase/nodels/cases0
  xCAT-test/autotest/testcase/noderange/cases0
  xCAT-test/autotest/testcase/noderm/cases0
  xCAT-test/autotest/testcase/regnotif/case0
  xCAT-test/autotest/testcase/restorexCATdb/cases0
  xCAT-test/autotest/testcase/rmdef/cases0
  xCAT-test/autotest/testcase/tabdump/cases0
  xCAT-test/autotest/testcase/tabgrep/cases0
  xCAT-test/autotest/testcase/tabprune/cases0
  xCAT-test/autotest/testcase/tabrestore/cases0
  xCAT-test/autotest/testcase/unregnotif/case0
  xCAT-test/autotest/testcase/xcatstanzafile/cases0
Labels: component:test, sprint2

#5356 Fix Ubuntu 18.04 postscript problem
  xCAT-server/share/xcat/install/scripts/post.ubuntu.common
Labels: sprint2

#5358 Abandon ssl2 support
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.localdisk
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite.ppc.redhat
  xCAT/postscripts/getcredentials.awk
  xCAT/postscripts/getpostscript.awk
  xCAT/postscripts/startsyncfiles
  xCAT/postscripts/startsyncfiles.awk
Labels: sprint2

#5364 Revert pull request #5358. Since it cause some side effects.
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.localdisk
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite.ppc.redhat
  xCAT/postscripts/getcredentials.awk
  xCAT/postscripts/getpostscript.awk
  xCAT/postscripts/startsyncfiles
  xCAT/postscripts/startsyncfiles.awk
Labels: sprint2

#5366 diskless support root options in addkcmdline
  xCAT-server/share/xcat/netboot/rh/dracut_033/xcatroot
Labels: sprint2

#5357 Add labels for xcatd test cases
  xCAT-test/autotest/testcase/analyze_log/case0
  xCAT-test/autotest/testcase/chvm/cases0
  xCAT-test/autotest/testcase/lsxcatd/cases0
  xCAT-test/autotest/testcase/xcatconfig/case0
  xCAT-test/autotest/testcase/xcatd/case0
  xCAT-test/autotest/testcase/xcatsnap/cases0
Labels: component:test, sprint2

#5361 remove date in updatenode message, for ticket Request removal of datefrom line in xCAT framework, idea? #5348
  xCAT/postscripts/xcatdsklspost
Labels: component:updatenode

#5340 Delete useless test cases
  xCAT-test/autotest/testcase/chkosimage/cases0
  xCAT-test/autotest/testcase/installation/Diskless_installation_flat_p8_le
  xCAT-test/autotest/testcase/installation/Full_installation_flat_p8_le
  xCAT-test/autotest/testcase/installation/reg_linux_SN_installation_hierarchy
  xCAT-test/autotest/testcase/installation/ubuntu_diskless_installation_vm
  xCAT-test/autotest/testcase/installation/ubuntu_full_installation_vm
  xCAT-test/autotest/testcase/makedhcp/cases0
  xCAT-test/autotest/testcase/makenetworks/cases0
  xCAT-test/autotest/testcase/mkdsklsnode/cases0
  xCAT-test/autotest/testcase/mknimimage/cases0
  xCAT-test/autotest/testcase/renergy/case_8233-E8B
  xCAT-test/autotest/testcase/renergy/case_9125-F2C
  xCAT-test/autotest/testcase/restartxcatd/cases0
  xCAT-test/autotest/testcase/rmdsklsnode/cases0
  xCAT-test/autotest/testcase/rmnimimage/cases0
  xCAT-test/autotest/testcase/xcat2nim/cases0
Labels: component:test, sprint2

#5369 Proper handle the -no_ssl2 argument of openssl s_client
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.localdisk
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite.ppc.redhat
  xCAT/postscripts/getcredentials.awk
  xCAT/postscripts/getpostscript.awk
  xCAT/postscripts/startsyncfiles
  xCAT/postscripts/startsyncfiles.awk
Labels: sprint2

#5367 add labels for makedhcp makedns xdcp xdsh makehosts command test cases
  xCAT-test/autotest/testcase/makedhcp/cases0
  xCAT-test/autotest/testcase/makedns/cases0
  xCAT-test/autotest/testcase/makehosts/cases0
  xCAT-test/autotest/testcase/xdcp/cases0
  xCAT-test/autotest/testcase/xdcp/cases1
  xCAT-test/autotest/testcase/xdsh/cases0
  xCAT-test/autotest/testcase/xdsh/cases1
Labels: component:test, sprint2

#5370 Sync up some bundle files after combining xcatd test cases
  xCAT-test/autotest/bundle/sles12.1_ppc64le.bundle
  xCAT-test/autotest/bundle/sles12.1_x86_64.bundle
  xCAT-test/autotest/bundle/sles12.2_ppc64le.bundle
  xCAT-test/autotest/bundle/sles12.2_x86_64.bundle
  xCAT-test/autotest/bundle/sles12_ppc64le.bundle
  xCAT-test/autotest/bundle/sles12_x86_64.bundle
  xCAT-test/autotest/bundle/ubuntu16.04.1_ppc64le.bundle
  xCAT-test/autotest/bundle/ubuntu16.04.1_x86_64.bundle
  xCAT-test/autotest/bundle/ubuntu16.04_ppc64le.bundle
  xCAT-test/autotest/bundle/ubuntu16.04_x86_64.bundle
Labels: component:test, sprint2

#5373 fix issue 2306: Need to clean up the temporary xCAT node during discovery regarding rcons
  xCAT-server/lib/xcat/plugins/nodediscover.pm
Labels: component:discovery

#5371 update hwinv table by updatenode -P geinv
  xCAT-server/lib/xcat/plugins/updatehwinv.pm
  xCAT-server/sbin/xcatconfig
  xCAT/postscripts/getinv
Labels: component:hw_control

#5372 refine doc for mkdef --template
  docs/source/guides/admin-guides/manage_clusters/common/deployment/create_img.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/discovery/manually_define.rst
Labels: type:documentation

#5377 Modify xcatd_stop test case to satisfy all rhels, sles and ubuntu os
  xCAT-test/autotest/testcase/xcatd/case0
Labels: component:test, sprint2

#5376 Thinker for the openssl s_client -no_ssl2 command line argument
  xCAT/postscripts/getcredentials.awk
  xCAT/postscripts/getpostscript.awk
  xCAT/postscripts/startsyncfiles.awk
Labels: sprint2

#5383 Tinker for the openssl -no_ssl2 command line argument
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.localdisk
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite.ppc.redhat
Labels: sprint1

#5387 Update for test case install_xCAT_on_ubuntu
  xCAT-test/autotest/testcase/go-xcat/bionic-ppc64el.sources.list
  xCAT-test/autotest/testcase/go-xcat/bionic-x86_64.sources.list
Labels: component:os_provision, component:test, sprint1

#5378 delete policy table change by xcat in pr 5371
  xCAT-server/lib/xcat/plugins/updatehwinv.pm
  xCAT-server/sbin/xcatconfig
  xCAT/postscripts/getinv
Labels: component:hw_control

#5390 Add check for leading zeroes in ip address when running makedns
  xCAT-server/lib/xcat/plugins/ddns.pm
Labels: component:dns

#5391 fix check for leading zeroes in ip address when running makehosts
  perl-xCAT/xCAT/NetworkUtils.pm
Labels: component:dns

#5346 rflash for ipmi machines enhancements
  xCAT-server/lib/xcat/plugins/ipmi.pm
Labels: component:hw_control

#5397 modify testcase of xcat-inventory environement based on code modify
  xCAT-test/autotest/testcase/xcat-inventory/cases.environment
  xCAT-test/autotest/testcase/xcat-inventory/templates/environment/gitrepo/postinstall/test1.postinstall
  xCAT-test/autotest/testcase/xcat-inventory/templates/environment/test.environments.osimage.yaml
Labels: component:automation

#5396 Add virtio_net to default network driver list for Ubuntu on ppc64el
  xCAT-server/share/xcat/netboot/ubuntu/genimage
Labels: sprint1

#5401 fix issue 5288, print out management node when summary for rflash
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_flash.py
  xCAT-openbmc-py/lib/python/agent/xcatagent/server.py
  xCAT-server/lib/perl/xCAT/AGENT.pm
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:openbmc

#5410 add power on after reset failure for rflash -d
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:hw_control

#5402 Draft setup chrony script
  xCAT/postscripts/setupntp
  xCAT/postscripts/setupntp.traditional
Labels: sprint1

#5328 Catch rflash firmware upload error
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:openbmc

#5412 Support REST boolean for reventlog resolved=
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_eventlog.py
Labels: component:openbmc

#5421 Workaround for Ubuntu 18.04 busybox bug
  xCAT-server/share/xcat/netboot/ubuntu/compute.ubuntu18.04.ppc64el.pkglist
  xCAT-server/share/xcat/netboot/ubuntu/compute.ubuntu18.04.x86_64.pkglist
  xCAT-server/share/xcat/netboot/ubuntu/genimage
Labels: component:os_provision, sprint1

#5404 Tweak makentp for chronyd
  xCAT-server/lib/xcat/plugins/makentp.pm
Labels: sprint1

#5416 put a delay of 3 seconds to untar the firmware file for rflash -d
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:hw_control

#5423 Fix issue 5360: dodiscovery does not handle lldp failures in some cases
  xCAT-genesis-scripts/usr/bin/dodiscovery
Labels: component:discovery

#5426 support sles12sp3 servicenode installation
  xCAT-server/share/xcat/install/scripts/post.xcat
  xCAT/postscripts/xcatpostinit1.install
  xCAT/postscripts/xcatpostinit1.service.yast2
Labels: sprint1

#5432 Enlarge the size of /boot partition for Ubuntu
  xCAT-server/share/xcat/install/scripts/pre.ubuntu
  xCAT-server/share/xcat/install/scripts/pre.ubuntu.ppc64
Labels: component:os_provision, sprint1

#5435 Add chrony to default Ubuntu 18.04 package lists
  xCAT-server/share/xcat/install/ubuntu/compute.ubuntu18.04.ppc64el.pkglist
  xCAT-server/share/xcat/install/ubuntu/compute.ubuntu18.04.x86_64.pkglist
  xCAT-server/share/xcat/netboot/ubuntu/compute.ubuntu18.04.ppc64el.pkglist
  xCAT-server/share/xcat/netboot/ubuntu/compute.ubuntu18.04.x86_64.pkglist
Labels: sprint1

#5438 Return and log error message if run by non-root users for config switch commands
  xCAT-server/share/xcat/scripts/configBNT
  xCAT-server/share/xcat/scripts/configMellanox
  xCAT-server/share/xcat/scripts/configonie
Labels: component:hw_control

#5437 rinstall flag and option
  docs/source/guides/admin-guides/references/man8/rinstall.8.rst
  xCAT-client/pods/man8/rinstall.8.pod
  xCAT-server/lib/xcat/plugins/destiny.pm
  xCAT-server/lib/xcat/plugins/rinstall.pm
Labels: component:os_provision

#5439 makedhcp check if mac format is valid
  xCAT-server/lib/xcat/plugins/dhcp.pm
  xCAT-test/autotest/testcase/makedhcp/cases0
Labels: component:dhcp

#5440 Use File::Temp::tmpnam() instead of POSIX::tmpnam()
  perl-xCAT/xCAT/DSHCLI.pm
Labels: sprint1

#5442 enhance lsdef Noderange format error
  xCAT-server/lib/xcat/plugins/DBobjectdefs.pm
Labels: component:obj_db_cmds

#5443 Use File::Temp::tmpnam() instead of POSIX::tmpnam()
  perl-xCAT/xCAT/PPCrflash.pm
  xCAT-server/lib/xcat/plugins/xdsh.pm
Labels: sprint1
