Repository xcat2/xcat-core, pull requests merged in 2018-06, with the labels that each got.

#5274 if not get valid pid when waitpid, sleep
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:openbmc

#5265 Add WARNING message if non-root user runs chtab command
  xCAT-server/sbin/chtab
Labels: component:obj_db_cmds

#5269 Refactor openbmc for better supporting redfish
  xCAT-server/lib/perl/xCAT/AGENT.pm
  xCAT-server/lib/perl/xCAT/OPENBMC.pm
  xCAT-server/lib/xcat/plugins/openbmc2.pm
Labels: component:redfish

#5119 show server name by default for Error and Warn message
  perl-xCAT/xCAT/Client.pm
  xCAT-test/autotest/testcase/rmdef/cases0
Labels: sprint1

#5267 Recording the Severity of log message into xCAT logs
  perl-xCAT/xCAT/MsgUtils.pm
  xCAT-server/sbin/xcatd
  xCAT/etc/rsyslog.d/xcat-cluster.conf
  xCAT/etc/rsyslog.d/xcat-compute.conf
Labels: type:usability

#5272 Create switchprobe link during xCAT-probe installation
  makerpm
  xCAT-probe/subcmds/switch_macmap
  xCAT-probe/xCAT-probe.spec
Labels: component:xcatprobe

#5261 check ip whether static for networkmanager config
  xCAT-probe/lib/perl/probe_utils.pm
Labels: component:xcatprobe

#5283 Using physical entity description OID to get Vendor information
  xCAT-server/lib/xcat/plugins/switchdiscover.pm
Labels: component:discovery, component:hw_control

#5277 Add redfish support perl part
  docs/source/guides/admin-guides/references/man5/nodehm.5.rst
  docs/source/guides/admin-guides/references/man7/group.7.rst
  docs/source/guides/admin-guides/references/man7/node.7.rst
  perl-xCAT/xCAT/Schema.pm
  xCAT-server/lib/xcat/plugins/redfish.pm
Labels: component:redfish

#5291 rpower/rsetboot stat for redfish
  xCAT-openbmc-py/lib/python/agent/common/rest.py
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/redfish_power.py
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/redfish_setboot.py
  xCAT-openbmc-py/lib/python/agent/hwctl/redfish_client.py
  xCAT-openbmc-py/lib/python/agent/xcatagent/base.py
  xCAT-openbmc-py/lib/python/agent/xcatagent/redfish.py
  xCAT-server/lib/xcat/plugins/redfish.pm
Labels: component:redfish, sprint1

#5280 Enhance xcattest to support label search
  xCAT-test/xcattest
Labels: component:test, sprint1

#5292 Failed to discover PDU
  xCAT-server/lib/xcat/plugins/switchdiscover.pm
Labels: component:discovery

#5281 support environment variables in osimage customized files
  perl-xCAT/xCAT/DSHCLI.pm
  perl-xCAT/xCAT/Schema.pm
  perl-xCAT/xCAT/Utils.pm
  xCAT-client/bin/xdsh
  xCAT-server/lib/perl/xCAT/Postage.pm
  xCAT-server/lib/perl/xCAT/Template.pm
  xCAT-server/lib/xcat/plugins/anaconda.pm
  xCAT-server/lib/xcat/plugins/genimage.pm
  xCAT-server/lib/xcat/plugins/packimage.pm
  xCAT-server/share/xcat/netboot/imgutils/imgutils.pm
  xCAT-server/share/xcat/netboot/rh/genimage
Labels: component:file_sync

#5298 Add security notification for 2018-06-12 OpenSSL reported issue - CVE-2018-0732
  docs/source/security/2018/20180612_openssl.rst
  docs/source/security/2018/index.rst
  docs/source/security/index.rst
Labels: type:documentation

#5303 enhance xcattest
  xCAT-test/xcattest
Labels: sprint2

#5300 Find correct template and postinstall file to build osimage for copycds -n command
  xCAT-server/lib/perl/xCAT/SvrUtils.pm
Labels: component:xcatd

#5296 build xnba config files from boottarget table
  xCAT-server/lib/xcat/plugins/xnba.pm
Labels: component:xcatd

#5308 fix error of xcatmn
  xCAT-probe/subcmds/xcatmn
Labels: component:xcatprobe

#5316 Specify the new GPG key 5619700D used for signing
  build-ubunturepo
Labels: component:packaging, component:security, sprint2

#5293 Refine option l of xcattest
  xCAT-test/xcattest
Labels: component:test

#5318 Hack travis.pl to resolve the GPG signing problem
  travis.pl
Labels: component:CI, sprint2

#5320 [go-xcat] Fix package version checking on Ubuntu 18.04
  xCAT-server/share/xcat/tools/go-xcat
Labels: sprint2

#5322 For Ubuntu 18.04 support, search a different place for Linux kernel and initrd
  xCAT-server/lib/xcat/plugins/debian.pm
Labels: component:os_provision, sprint2

#5326 Enhance framework for xcatprobe to have function to query xCAT tables, be more transparent on what probe is doing for daemon attribute
  xCAT-probe/subcmds/xcatmn
Labels: component:xcatprobe, type:usability

#5324 Revise Ubuntu 18.04 package list, add ifupdown, remove ntp and ntpdate
  xCAT-server/share/xcat/install/ubuntu/compute.ubuntu18.04.ppc64el.pkglist
  xCAT-server/share/xcat/netboot/ubuntu/compute.ubuntu18.04.ppc64el.pkglist
  xCAT-server/share/xcat/netboot/ubuntu/compute.ubuntu18.04.x86_64.pkglist
Labels: component:os_provision, sprint2

#5310 modify confluent doc based on verification
  docs/source/advanced/confluent/client/confluent_client.rst
  docs/source/advanced/confluent/server/confluent_server.rst
Labels: type:documentation

#5331 modify man page of rcons about exit code
  docs/source/guides/admin-guides/references/man1/rcons.1.rst
  xCAT-client/pods/man1/rcons.1.pod
Labels: type:documentation

#5332 modify renergy powerusage/temperature Usage
  perl-xCAT/xCAT/Usage.pm
Labels: component:hw_control

#5337 Add model type for 'stratton' boxes, 8001-12C model type in firmware flashing
  xCAT-server/lib/xcat/plugins/ipmi.pm
Labels: component:firmware, type:bug

#5338 add --nodeps in confluent doc for rpm install
  docs/source/advanced/confluent/server/confluent_server.rst
Labels: type:documentation

#5315 Add labels for all hardware control test case
  xCAT-test/autotest/testcase/UT_openbmc/reventlog_resolved_cases0
  xCAT-test/autotest/testcase/UT_openbmc/rflash_cases0
  xCAT-test/autotest/testcase/UT_openbmc/rinv_cases0
  xCAT-test/autotest/testcase/UT_openbmc/rspconfig_cases0
  xCAT-test/autotest/testcase/UT_openbmc/supported_commands_case0
  xCAT-test/autotest/testcase/rbeacon/cases0
  xCAT-test/autotest/testcase/reventlog/cases0
  xCAT-test/autotest/testcase/rflash/rflash_openbmc.0
  xCAT-test/autotest/testcase/rinv/cases0
  xCAT-test/autotest/testcase/rinv/cases2
  xCAT-test/autotest/testcase/rpower/cases0
  xCAT-test/autotest/testcase/rsetboot/cases0
  xCAT-test/autotest/testcase/rspconfig/cases0
  xCAT-test/autotest/testcase/rspconfig/cases1
  xCAT-test/autotest/testcase/rvitals/cases0
  xCAT-test/autotest/testcase/rvitals/cases1
Labels: component:test, sprint2

#5343 Add compute.ubuntu18.04.x86_64.pkglist for Ubuntu 18.04 x86-64 support
  xCAT-server/share/xcat/install/ubuntu/compute.ubuntu18.04.x86_64.pkglist
Labels: component:os_provision, sprint2

#5342 Fix $kernelpath for Ubuntu 18.04 on ppc64el
  xCAT-server/lib/xcat/plugins/debian.pm
Labels: component:os_provision, sprint2

#5335 create HA doc
  docs/source/references/coral/ha/ha_mgmt_node_with_shared_data.rst
  docs/source/references/coral/ha/index.rst
  docs/source/references/coral/index.rst
Labels: sprint2

#5352 fix Statelite provision hung at ``netbooting`` for rhels 6.10 in PPC64
  xCAT-server/lib/xcat/plugins/statelite.pm
Labels: sprint2
