Repository xcat2/xcat-core, pull requests merged in 2018-05, with the labels that each got.

#5138 Improve xCAT uninstall documentation
  docs/source/guides/install-guides/maintenance/uninstall_xcat.rst
Labels: type:documentation

#5156 enhance chdef testcase for postscripts
  xCAT-test/autotest/testcase/chdef/cases0
Labels: component:test

#5155 update test case 'xcatd_start' for issue 5152
  xCAT-test/autotest/testcase/xcatd/case0
Labels: component:test

#5149 Handle invalid tables in REST API
  docs/source/advanced/restapi/restapi_resource/restapi_reference.rst
  xCAT-server/xCAT-wsapi/xcatws.cgi
  xCAT-test/autotest/testcase/restapi/table/cases0
Labels: component:restapi, type:documentation

#5144 Support nodeset <switch> osimage command for cumulus switch
  xCAT-server/lib/xcat/plugins/dhcp.pm
  xCAT-server/lib/xcat/plugins/onie.pm
Labels: component:design, component:xcatd, type:support

#5061 report ipmi_debug message under node name (#5033)
  xCAT-server/lib/perl/xCAT/IPMI.pm
  xCAT-server/lib/xcat/plugins/ipmi.pm
Labels: type:usability

#5162 refine the nodeset of cumulus osimage
  xCAT-server/lib/xcat/plugins/onie.pm
Labels: component:coral, cumulus

#5164 Fix typo of test case export_import_single_ppc_by_json
  xCAT-test/autotest/testcase/xcat-inventory/cases.node
Labels: component:test

#5166 TravisCI wording and JSON format check
  travis.pl
Labels: component:CI, component:test

#5143 REST API for OpenBMC nodes
  xCAT-server/xCAT-wsapi/xcatws.cgi
  xCAT-test/autotest/restapi.template
  xCAT-test/autotest/testcase/restapi/node/cases0
  xCAT-test/autotest/testcase/restapi/node/cases1
  xCAT-test/restapitest
Labels: component:openbmc, component:restapi

#5163 Add some logs for bmcdiscover
  xCAT-server/lib/xcat/plugins/bmcdiscover.pm
Labels: component:hw_control

#5113 add rspconfig test cases
  xCAT-test/autotest/testcase/rspconfig/cases1
Labels: component:test

#5173 Add Copycds/nodeset/syncfiles support to onie switches documentation
  docs/source/advanced/networks/onie_switches/os_cumulus/install.rst
  docs/source/advanced/networks/onie_switches/os_cumulus/manage.rst
  docs/source/advanced/networks/onie_switches/os_cumulus/prepare.rst
Labels: type:documentation

#5172 Add REST API beacon status function
  docs/source/advanced/restapi/restapi_resource/restapi_reference.rst
  xCAT-server/xCAT-wsapi/xcatws.cgi
  xCAT-test/autotest/testcase/restapi/node/cases1
Labels: component:restapi

#5179 Add test for issue 922
  xCAT-test/autotest/testcase/installation/reg_linux_diskfull_installation_flat
  xCAT-test/autotest/testcase/installation/reg_linux_diskfull_installation_hierarchy
  xCAT-test/autotest/testcase/installation/reg_linux_diskless_installation_flat
  xCAT-test/autotest/testcase/installation/reg_linux_diskless_installation_hierarchy
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_flat
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_hierarchy_by_nfs
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_hierarchy_by_ramdisk
Labels: component:test, sprint2

#5174 REST API handle no key match for tables
  xCAT-server/xCAT-wsapi/xcatws.cgi
  xCAT-test/autotest/testcase/restapi/table/cases0
Labels: component:restapi

#5157 Add log service and log record in xcatprobe xcatmn
  xCAT-probe/lib/perl/probe_utils.pm
  xCAT-probe/subcmds/xcatmn
Labels: component:xcatprobe

#5182 Add test case for xcatprobe detect_dhcpd command
  xCAT-test/autotest/testcase/probe/detect_dhcpd
Labels: component:test, sprint2

#5185 OpenBMC rinv more specific REST calls
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_flash.py
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_inventory.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
Labels: component:openbmc

#5184 make store_fd does not thow exception and the client could be closed.
  perl-xCAT/xCAT/Table.pm
Labels: sprint2

#5190 add iputils into compute.sles11.pkglist
  xCAT-server/share/xcat/netboot/sles/compute.sles11.pkglist
Labels: component:os_provision

#5187 use tar as the default archive method instead of cpio
  docs/source/guides/admin-guides/references/man1/packimage.1.rst
  xCAT-client/pods/man1/packimage.1.pod
  xCAT-server/lib/xcat/plugins/packimage.pm
Labels: component:os_provision

#5189 modify ipmi rsp check to support openbmc ipmi interface
  xCAT-server/lib/perl/xCAT/IPMI.pm
Labels: component:hw_control

#5194 Force chain to be standby if only runcmd/ondiscover is specified for chain attribute
  xCAT-server/lib/xcat/plugins/destiny.pm
Labels: component:discovery

#5188 add a case to support regex for makehosts
  xCAT-test/autotest/testcase/makehosts/cases0
Labels: component:test

#5195 Prefer HWE netboot where available in Ubuntu
  xCAT-server/lib/xcat/plugins/debian.pm
Labels: component:os_provision

#5208 fix issue for using waitpid in openbmc perl
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:openbmc

#5205 Modify case bmcdiscover_range_w to cover boston server
  xCAT-test/autotest/testcase/bmcdiscover/cases0
Labels: component:test, sprint2

#5211 Display only OpenBMC usage
  perl-xCAT/xCAT/Usage.pm
  xCAT-server/lib/xcat/plugins/openbmc2.pm
Labels: component:openbmc

#5206 Fix ERR message when running ondiscover in the chain table
  xCAT-server/lib/xcat/plugins/destiny.pm
Labels: component:discovery

#5218 Remove non-root user test from statelite provision
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_flat
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_hierarchy_by_nfs
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_hierarchy_by_ramdisk
Labels: component:test, sprint2

#5201 OpenBMC rinv multiple options
  docs/source/guides/admin-guides/references/man1/rinv.1.rst
  perl-xCAT/xCAT/Usage.pm
  xCAT-client/pods/man1/rinv.1.pod
  xCAT-openbmc-py/lib/python/agent/hwctl/executor/openbmc_inventory.py
  xCAT-openbmc-py/lib/python/agent/hwctl/inventory.py
  xCAT-openbmc-py/lib/python/agent/xcatagent/openbmc.py
  xCAT-server/lib/xcat/plugins/openbmc2.pm
Labels: component:openbmc

#5219 fix 5200 do not restart_ib_driver_service by default
  xCAT/postscripts/configib
Labels: component:network

#5225 Add non-root user check for diskless provision
  xCAT-test/autotest/testcase/packimg/cases0
Labels: component:test, sprint2

#5215 there are several xcatd SSL process remaining
  xCAT-server/sbin/xcatd
Labels: sprint2

#5137 Simplify cuda_power9_setup
  xCAT/postscripts/cuda_power9_setup
Labels: component:postscripts

#5231 Thinker xCAT/postscripts/cuda_power9_setup,
  xCAT/postscripts/cuda_power9_setup
Labels: component:postscripts, sprint2

#5230 fix issue Non-root user can not run ping on ubuntu 14.4.4 diskless #5227
  xCAT-server/lib/xcat/plugins/packimage.pm
  xCAT-server/share/xcat/netboot/ubuntu/genimage
Labels: component:os_provision

#5226 Modify output message for PDU outlet state
  xCAT-server/lib/xcat/plugins/openbmc.pm
  xCAT-server/lib/xcat/plugins/openbmc2.pm
  xCAT-server/lib/xcat/plugins/pdu.pm
Labels: component:xcatd, type:usability

#5220 the error message of *def command is disordered when running internally
  xCAT-server/lib/xcat/plugins/DBobjectdefs.pm
  xCAT-server/lib/xcat/plugins/bmcdiscover.pm
Labels: component:xcatd, type:support

#5229 using --nosyncfiles to ignore sync files to root image when packimage
  docs/source/guides/admin-guides/references/man1/packimage.1.rst
  xCAT-client/pods/man1/packimage.1.pod
  xCAT-server/lib/xcat/plugins/packimage.pm
Labels: component:os_provision

#5212 Verify commit owner id
  travis.pl
Labels: component:test

#5234 update xcat-inventory test cases according to the modification in xcat-inventory 0.1.2
  xCAT-test/autotest/testcase/xcat-inventory/cases.common
  xCAT-test/autotest/testcase/xcat-inventory/cases.node
  xCAT-test/autotest/testcase/xcat-inventory/cases.osimage.validation
Labels: sprint2

#5243 add test cases for xcat-inventory import -d for osimage inventory directory
  xCAT-test/autotest/testcase/xcat-inventory/cases.osimage.import_from_osimage_dir
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/cluster.json
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage/definition.json
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage/test_myimage.stanza
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage/tmp/test_myimage/exlist
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage/tmp/test_myimage/otherpkglist
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage/tmp/test_myimage/partitionfile
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage/tmp/test_myimage/postinstall
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage/tmp/test_myimage/synclists
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage2/definition.json
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage2/test_myimage2.stanza
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage2/tmp/test_myimage2/exlist
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage2/tmp/test_myimage2/otherpkglist
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage2/tmp/test_myimage2/partitionfile
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage2/tmp/test_myimage2/postinstall
  xCAT-test/autotest/testcase/xcat-inventory/templates/cluster_invdir/osimage/test_myimage2/tmp/test_myimage2/synclists
Labels: component:test

#5244 Add one test case for xcat-inventory export option -f
  xCAT-test/autotest/testcase/xcat-inventory/cases.common
Labels: sprint2

#5202 Add resource check in xcatmn
  xCAT-probe/subcmds/xcatmn
Labels: component:xcatprobe

#5253 Update the testcase to cover the changes in #5119
  xCAT-test/autotest/testcase/UT_openbmc/reventlog_resolved_cases0
  xCAT-test/autotest/testcase/UT_openbmc/rflash_cases0
  xCAT-test/autotest/testcase/UT_openbmc/rspconfig_cases0
  xCAT-test/autotest/testcase/addkitcomp/case0
  xCAT-test/autotest/testcase/chdef/cases0
  xCAT-test/autotest/testcase/chvm/cases0
  xCAT-test/autotest/testcase/lsdef/cases0
  xCAT-test/autotest/testcase/nodeset/cases0
  xCAT-test/autotest/testcase/packimg/cases0
  xCAT-test/autotest/testcase/pdu/case0
  xCAT-test/autotest/testcase/pping/cases0
  xCAT-test/autotest/testcase/restapi/table/cases0
  xCAT-test/autotest/testcase/reventlog/cases0
  xCAT-test/autotest/testcase/rflash/rflash_openbmc.0
  xCAT-test/autotest/testcase/rinv/cases0
  xCAT-test/autotest/testcase/rmkitcomp/case0
  xCAT-test/autotest/testcase/rpower/cases0
  xCAT-test/autotest/testcase/rsetboot/cases0
  xCAT-test/autotest/testcase/rspconfig/cases0
  xCAT-test/autotest/testcase/rspconfig/cases1
  xCAT-test/autotest/testcase/xcat-inventory/cases.node
  xCAT-test/autotest/testcase/xcat-inventory/cases.site
  xCAT-test/autotest/testcase/xcat-inventory/validatehelper
  xCAT-test/autotest/testcase/xcatd/case0
  xCAT-test/autotest/testcase/xdsh/cases0
Labels: sprint2

#5240 update xcat inventory osimage export and import cases
  xCAT-test/autotest/testcase/xcat-inventory/cases.osimage
Labels: component:test

#5247 Increase packet size of recv()
  xCAT-server/sbin/xcatd
Labels: component:discovery, component:xcatd

#5258 Fix code error to generate the right socket file name based on the caller PID
  xCAT-server/lib/perl/xCAT/OPENBMC.pm
  xCAT-server/lib/xcat/plugins/openbmc2.pm
Labels: component:openbmc

#5120 Update the CUDA installation test script
  xCAT-test/autotest/testcase/cuda/rhel-cuda-diskless-install.sh
Labels: component:test

#5251 redirect wget output to /tmp/wget.log
  xCAT-server/share/xcat/install/scripts/post.xcat
Labels: component:os_provision, component:postscripts, type:usability

#5264 Merge master to 2.14 for 2.14.1 release(2)
  xCAT-server/share/xcat/install/scripts/post.xcat
Labels: component:packaging

#5197 Add back ntp-wait for building genesis-base on pegas
  xCAT-genesis-builder/buildrpm
  xCAT-genesis-builder/cmdlist_check
Labels: component:discovery

#5268 Add release information for 2.14.1
  docs/source/conf.py
  docs/source/overview/xcat2_release.rst
Labels: type:documentation

#5270 modify nodestat usage and manpage for `-f|--useping`
  docs/source/guides/admin-guides/references/man1/nodestat.1.rst
  xCAT-client/pods/man1/nodestat.1.pod
  xCAT-server/lib/xcat/plugins/nodestat.pm
Labels: type:usability
