Repository xcat2/xcat-core, pull requests merged in 2018-10, with the labels that each got.

#5681 Add two disc ID for rhels8.0
  perl-xCAT/xCAT/data/discinfo.pm
Labels: component:xcatd

#5689 refine xdsh_t case to fix issue #5687
  xCAT-test/autotest/testcase/xdsh/cases0
Labels: component:test, sprint2

#5690 fix issue 5596, recover env for case rinv_wrongbmcpasswd
  xCAT-test/autotest/testcase/rinv/cases0
Labels: component:test

#5691 fix issue 5633, use noempty file to check tftp service
  xCAT-probe/lib/perl/probe_utils.pm
Labels: component:xcatprobe

#5686 fix xcatprobe xcatmn issues 5677&5678
  xCAT-probe/debian/control
  xCAT-probe/lib/perl/probe_utils.pm
  xCAT-probe/subcmds/xcatmn
  xCAT-probe/xCAT-probe.spec
Labels: component:xcatprobe

#5669 Formatting and spelling fixes for some man pages
  docs/source/guides/admin-guides/manage_clusters/common/deployment/use_kernel_patch.rst
  docs/source/guides/admin-guides/references/man1/chzone.1.rst
  docs/source/guides/admin-guides/references/man1/db2sqlsetup.1.rst
  docs/source/guides/admin-guides/references/man1/lstree.1.rst
  docs/source/guides/admin-guides/references/man1/mkdsklsnode.1.rst
  docs/source/guides/admin-guides/references/man1/mkzone.1.rst
  docs/source/guides/admin-guides/references/man1/nodechmac.1.rst
  docs/source/guides/admin-guides/references/man1/renergy.1.rst
  docs/source/guides/admin-guides/references/man1/rinv.1.rst
  docs/source/guides/admin-guides/references/man1/rmzone.1.rst
  docs/source/guides/admin-guides/references/man1/rspconfig.1.rst
  docs/source/guides/admin-guides/references/man1/sinv.1.rst
  docs/source/guides/admin-guides/references/man1/xdcp.1.rst
  docs/source/guides/admin-guides/references/man1/xdsh.1.rst
  docs/source/guides/admin-guides/references/man1/xdshbak.1.rst
  docs/source/guides/admin-guides/references/man5/nodegroup.5.rst
  docs/source/guides/admin-guides/references/man5/site.5.rst
  docs/source/guides/admin-guides/references/man7/group.7.rst
  perl-xCAT/xCAT/Schema.pm
  xCAT-client/pods/man1/chzone.1.pod
  xCAT-client/pods/man1/db2sqlsetup.1.pod
  xCAT-client/pods/man1/lstree.1.pod
  xCAT-client/pods/man1/mkdsklsnode.1.pod
  xCAT-client/pods/man1/mkzone.1.pod
  xCAT-client/pods/man1/nodechmac.1.pod
  xCAT-client/pods/man1/renergy.1.pod
  xCAT-client/pods/man1/rinv.1.pod
  xCAT-client/pods/man1/rmzone.1.pod
  xCAT-client/pods/man1/rspconfig.1.pod
  xCAT-client/pods/man1/sinv.1.pod
  xCAT-client/pods/man1/xdcp.1.pod
  xCAT-client/pods/man1/xdsh.1.pod
  xCAT-client/pods/man1/xdshbak.1.pod
Labels: type:documentation

#5646 Improve flow and grammar for openbmc python installation doc
  docs/source/advanced/goconserver/index.rst
  docs/source/advanced/restapi/restapi_setup/restapi_setup.rst
  docs/source/guides/admin-guides/basic_concepts/xcat_db/regexp_db.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/syncfile/syncfile_synclist_file.rst
  docs/source/guides/admin-guides/references/man1/piflash.1.rst
  docs/source/references/coral/cluster_mgmt/scalability/python/install/rpm.rst
  xCAT-client/pods/man1/piflash.1.pod
Labels: type:documentation

#5693 enhance xcatmn for issue 4606
  xCAT-probe/subcmds/xcatmn
Labels: component:xcatprobe, sprint2

#5697 fix issue 5694, not try to install tree for xCAT-probe
  xCAT-probe/debian/control
  xCAT-probe/lib/perl/probe_utils.pm
  xCAT-probe/subcmds/xcatmn
  xCAT-probe/xCAT-probe.spec
Labels: component:xcatprobe

#5675 xCAT name consistency
  docs/source/index.rst
  perl-xCAT/README
  xCAT-OpenStack-baremetal/xpod2man
  xCAT-SoftLayer/xpod2man
  xCAT-UI/debian/control
  xCAT-UI/lib/ui.php
  xCAT-UI/service.php
  xCAT-UI/xCAT-UI.spec
  xCAT-client/xpod2man
  xCAT-confluent/xpod2man
  xCAT-server/share/xcat/tools/go-xcat
  xCAT-vlan/xpod2man
Labels: type:documentation

#5672 [Docu] Remove "Install NVIDIA Management Library"
  docs/source/advanced/gpu/nvidia/repo/index.rst
  docs/source/advanced/gpu/nvidia/repo/nvml.rst
Labels: type:documentation

#5713 fix enablekdump for redhat7.6 and 7.6-alt nfs vers 4 support
  xCAT/postscripts/enablekdump
Labels: component:os_provision

#5714 Update some outdated test cases
  xCAT-test/autotest/testcase/UT_openbmc/reventlog_resolved_cases0
  xCAT-test/autotest/testcase/UT_openbmc/rspconfig_cases0
  xCAT-test/autotest/testcase/installation/setup_vm
  xCAT-test/autotest/testcase/rspconfig/cases1
Labels: component:test

#5725 classify deployment log and updatenode log
  xCAT-server/share/xcat/install/scripts/post.xcat
  xCAT-server/share/xcat/install/scripts/post.xcat.ng
  xCAT-server/share/xcat/netboot/rh/dracut/xcatroot
  xCAT-server/share/xcat/netboot/rh/dracut_033/xcatroot
  xCAT-server/share/xcat/netboot/rh/dracut_047/xcatroot
  xCAT/postscripts/xcatdsklspost
  xCAT/postscripts/xcatinstallpost
Labels: component:os_provision

#5727 Process --noupdateinitrd and --ignorekernelchk flags for rinstall
  docs/source/guides/admin-guides/references/man5/site.5.rst
  docs/source/guides/admin-guides/references/man8/rinstall.8.rst
  xCAT-client/pods/man8/rinstall.8.pod
  xCAT-server/lib/xcat/plugins/rinstall.pm
Labels: component:os_provision

#5732 Add reventlog to hw management list
  docs/source/guides/admin-guides/manage_clusters/ppc64le/management/advanced/index.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/management/advanced/reventlog.rst
  docs/source/references/coral/known_issues/index.rst
  docs/source/references/coral/known_issues/openbmc/2_13_8.rst
  docs/source/references/coral/known_issues/openbmc/SW402273.rst
  docs/source/references/coral/known_issues/openbmc/SW404161.rst
  docs/source/references/coral/known_issues/openbmc/SW406771.rst
  docs/source/references/coral/known_issues/openbmc/SW407037.rst
  docs/source/references/coral/known_issues/openbmc/index.rst
Labels: type:documentation

#5737 nodeset ubuntu16.04.5 x86_64 support
  xCAT-server/lib/xcat/plugins/debian.pm
Labels: component:os_provision

#5736 enhance test case setup_vm
  xCAT-test/autotest/testcase/installation/setup_vm
Labels: component:test, sprint1

#5743 log tag support for common scripts
  xCAT-server/share/xcat/install/scripts/post.xcat
  xCAT/postscripts/configeth
  xCAT/postscripts/nicutils.sh
  xCAT/postscripts/ospkgs
  xCAT/postscripts/otherpkgs
  xCAT/postscripts/remoteshell
  xCAT/postscripts/syncfiles
  xCAT/postscripts/syslog
  xCAT/postscripts/xcatdsklspost
  xCAT/postscripts/xcatpostinit1.netboot
  xCAT/postscripts/xcatpostinit1.service
Labels: sprint1

#5749 log tag support for servicenode and fix updatenode failed test cases
  xCAT/postscripts/otherpkgs
  xCAT/postscripts/servicenode
  xCAT/postscripts/xcatdsklspost
Labels: sprint1

#5717 fix issue 5700, support site.httpport to be used in discovery in xcatprobe
  xCAT-probe/subcmds/discovery
Labels: component:xcatprobe

#5715 fix issue 5701, support site.httpport setting for xcatmn check
  xCAT-probe/lib/perl/probe_utils.pm
  xCAT-probe/subcmds/xcatmn
Labels: component:xcatprobe

#5723 Do not restart service openibd in the installation stage
  xCAT-server/share/xcat/ib/scripts/Mellanox/mlnxofed_ib_install.v2
Labels: component:infiniband, sprint1

#5752 xCAT-genesis-builder - Revise the error handling for directory detecting
  xCAT-genesis-builder/xCAT-genesis-base.spec
Labels: sprint1
