Repository xcat2/xcat-core, pull requests merged in 2019-07, with the labels that each got.

#6370 Add new Edgecore Mac address to switchinfo file
  perl-xCAT/xCAT/data/switchinfo.pm
Labels: component:discovery, cumulus, type:support

#6371 Merge from master to 2.15 branch. (1)
  perl-xCAT/xCAT/data/switchinfo.pm
Labels: priority:normal

#6374 Simplify the Release Notes from xCAT 2.12 and newer
  docs/source/conf.py
  docs/source/overview/_files/2.12.x.csv
  docs/source/overview/_files/2.13.x.csv
  docs/source/overview/_files/2.14.x.csv
  docs/source/overview/_files/2.15.x.csv
  docs/source/overview/xcat2_release.rst
Labels: type:documentation

#6376 Merge from master to 2.15 branch for 2.15.0 release. (2)
  docs/source/conf.py
  docs/source/overview/_files/2.12.x.csv
  docs/source/overview/_files/2.13.x.csv
  docs/source/overview/_files/2.14.x.csv
  docs/source/overview/_files/2.15.x.csv
  docs/source/overview/xcat2_release.rst
  perl-xCAT/xCAT/SLP.pm
  xCAT-server/lib/perl/xCAT/IPMI.pm
Labels: priority:normal

#6369 Adding some notes to clarify genesis-base workaround for Power9 Hardware
  docs/source/references/coral/known_issues/genesis_base.rst
Labels: type:documentation

#6382 Remove kit links
  docs/source/guides/admin-guides/references/man1/addkit.1.rst
  docs/source/guides/admin-guides/references/man1/addkitcomp.1.rst
  docs/source/guides/admin-guides/references/man1/buildkit.1.rst
  docs/source/guides/admin-guides/references/man1/chkkitcomp.1.rst
  docs/source/guides/admin-guides/references/man1/lskit.1.rst
  docs/source/guides/admin-guides/references/man1/lskitcomp.1.rst
  docs/source/guides/admin-guides/references/man1/lskitdeployparam.1.rst
  docs/source/guides/admin-guides/references/man1/rmkit.1.rst
  docs/source/guides/admin-guides/references/man1/rmkitcomp.1.rst
  xCAT-buildkit/bin/buildkit
  xCAT-buildkit/pods/man1/buildkit.1.pod
  xCAT-buildkit/xCAT-buildkit.spec
  xCAT-client/debian/xcat-client.links
  xCAT-client/pods/man1/addkit.1.pod
  xCAT-client/pods/man1/addkitcomp.1.pod
  xCAT-client/pods/man1/chkkitcomp.1.pod
  xCAT-client/pods/man1/lskit.1.pod
  xCAT-client/pods/man1/lskitcomp.1.pod
  xCAT-client/pods/man1/lskitdeployparam.1.pod
  xCAT-client/pods/man1/rmkit.1.pod
  xCAT-client/pods/man1/rmkitcomp.1.pod
  xCAT-client/xCAT-client.spec
Labels: component:kit

#6384 Merge from master to 2.15 branch for 2.15.0 release. (3)
  docs/source/guides/admin-guides/references/man1/addkit.1.rst
  docs/source/guides/admin-guides/references/man1/addkitcomp.1.rst
  docs/source/guides/admin-guides/references/man1/buildkit.1.rst
  docs/source/guides/admin-guides/references/man1/chkkitcomp.1.rst
  docs/source/guides/admin-guides/references/man1/lskit.1.rst
  docs/source/guides/admin-guides/references/man1/lskitcomp.1.rst
  docs/source/guides/admin-guides/references/man1/lskitdeployparam.1.rst
  docs/source/guides/admin-guides/references/man1/rmkit.1.rst
  docs/source/guides/admin-guides/references/man1/rmkitcomp.1.rst
  docs/source/references/coral/known_issues/genesis_base.rst
  xCAT-buildkit/bin/buildkit
  xCAT-buildkit/pods/man1/buildkit.1.pod
  xCAT-buildkit/xCAT-buildkit.spec
  xCAT-client/debian/xcat-client.links
  xCAT-client/pods/man1/addkit.1.pod
  xCAT-client/pods/man1/addkitcomp.1.pod
  xCAT-client/pods/man1/chkkitcomp.1.pod
  xCAT-client/pods/man1/lskit.1.pod
  xCAT-client/pods/man1/lskitcomp.1.pod
  xCAT-client/pods/man1/lskitdeployparam.1.pod
  xCAT-client/pods/man1/rmkit.1.pod
  xCAT-client/pods/man1/rmkitcomp.1.pod
  xCAT-client/xCAT-client.spec
Labels: priority:normal

#6385 Remove kits from Ubuntu and go-xcat
  xCAT-server/share/xcat/tools/go-xcat
  xCAT/debian/control
  xCATsn/debian/control
Labels: component:kit

#6387 Merge from master to 2.15 branch for 2.15.0 release. (4)
  xCAT-server/share/xcat/tools/go-xcat
  xCAT/debian/control
  xCATsn/debian/control
Labels: priority:normal
