Repository xcat2/xcat-core, pull requests merged in 2019-12, with the labels that each got.

#6501 Add support for provision SLE15 diskless compute
  xCAT-server/share/xcat/netboot/sles/compute.sle15.pkglist
  xCAT-server/share/xcat/netboot/sles/compute.sle15.x86_64.pkglist
  xCAT-server/share/xcat/netboot/sles/dracut_033/xcatroot
  xCAT-server/share/xcat/netboot/sles/genimage
Labels: component:os_provision, type:support

#6380 Automatically find first unlocked user slot
  xCAT-genesis-scripts/usr/bin/bmcsetup
Labels: status:require-cla

#6503 Add KVM CPU mode to vm.othersettings (see issue #4182)
  perl-xCAT/xCAT/Schema.pm
  xCAT-server/lib/xcat/plugins/kvm.pm
Labels: component:virtualization

#6504 Remove perl-IO-Stty requirement from xCAT spec
  xCAT/xCAT.spec
  xCATsn/xCATsn.spec
Labels: component:packaging, type:support

#6499 Restart libssl1.1 without asking for regression Ubuntu pkg install2
  xCAT-test/autotest/testcase/migration/ubuntu_migration1_vm
Labels: component:test

#6507 Update man pages for vm.othersettings
  docs/source/guides/admin-guides/references/man5/vm.5.rst
  docs/source/guides/admin-guides/references/man7/group.7.rst
  docs/source/guides/admin-guides/references/man7/node.7.rst
Labels: type:documentation

#6509 Update return code for OpenBMC testcase
  xCAT-test/autotest/testcase/UT_openbmc/reventlog_resolved_cases0
Labels: component:test

#6510 Modify logrotate conf file to reduce log missing
  xCAT-server/share/xcat/conf/goconslogrotate
  xCAT/etc/logrotate.d/xcat
Labels: component:console, component:goconserver, component:xcatd, type:support

#6511 BMC password change script
  xCAT-server/share/xcat/scripts/BMC_change_password.sh
Labels: component:openbmc

#6513 Update BMC_change_password.sh usage
  xCAT-server/share/xcat/scripts/BMC_change_password.sh
Labels: component:openbmc, type:usability

#6514 Update message for BMC password change
  xCAT-server/share/xcat/scripts/BMC_change_password.sh
Labels: component:openbmc, type:usability
