Repository xcat2/xcat-core, pull requests merged in 2019-11, with the labels that each got.

#6468 Fix formatting in postscripts doc
  docs/source/guides/admin-guides/manage_clusters/common/deployment/prepostscripts/post_script.rst
Labels: type:documentation

#6471 Restart libssl1.1 without asking for regression Ubuntu pkg install
  xCAT-test/autotest/testcase/migration/ubuntu_migration2_vm
Labels: component:test

#6472 link package list from rh to centos
  xCAT-server/share/xcat/netboot/centos/compute.centos8.ppc64le.exlist
  xCAT-server/share/xcat/netboot/centos/compute.centos8.ppc64le.pkglist
  xCAT-server/share/xcat/netboot/centos/compute.centos8.ppc64le.postinstall
  xCAT-server/share/xcat/netboot/centos/compute.centos8.x86_64.exlist
  xCAT-server/share/xcat/netboot/centos/compute.centos8.x86_64.pkglist
  xCAT-server/share/xcat/netboot/centos/compute.centos8.x86_64.postinstall
Labels: component:packaging

#6474 Display packages and version before go-xcat install
  xCAT-server/share/xcat/tools/go-xcat
Labels: component:go-xcat

#6475 Fix repodata files permission in xcat-dep
  builddep.sh
Labels: component:packaging

#6476 Fix broken doc links
  docs/source/advanced/hierarchy/configure_dhcp.rst
  docs/source/advanced/hierarchy/define_service_node.rst
  docs/source/advanced/performance_tuning/httpd_tuning.rst
  docs/source/advanced/restapi/restapi_usage/restapi_usage.rst
  docs/source/developers/guides/docs/doc_guidelines.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/cfg_partition.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/enable_kdump.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/cfg_partition.rst
Labels: type:documentation

#6478 linux_diskless_kdump testcase enhancement
  xCAT-test/autotest/testcase/kdump/linux_diskless_kdump
Labels: component:test

#6481 Modify pkglist to clean up genimage error messages
  xCAT-server/share/xcat/netboot/centos/dracut_047
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.ppc64le.pkglist
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.x86_64.pkglist
  xCAT-server/share/xcat/netboot/rh/genimage
  xCAT-server/share/xcat/netboot/rh/service.rhels8.ppc64le.pkglist
  xCAT-server/share/xcat/netboot/rh/service.rhels8.x86_64.pkglist
Labels: rh8

#6482 Use nslookup option type=A for xcatprobe xcatmn command
  xCAT-probe/lib/perl/probe_utils.pm
  xCAT-probe/subcmds/xcatmn
Labels: component:xcatprobe

#6480 OpenBMC Thermal Mode [Perl]
  docs/source/guides/admin-guides/references/man1/rspconfig.1.rst
  perl-xCAT/xCAT/Usage.pm
  xCAT-client/pods/man1/rspconfig.1.pod
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:openbmc

#6483 OpenBMC Thermal Mode [Python]
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
  xCAT-openbmc-py/lib/python/agent/xcatagent/openbmc.py
  xCAT-server/lib/xcat/plugins/openbmc2.pm
Labels: component:openbmc

#6484 Add OpenBMC thermal mode testcases
  xCAT-test/autotest/testcase/UT_openbmc/rinv_cases0
  xCAT-test/autotest/testcase/UT_openbmc/rspconfig_cases0
Labels: component:openbmc, component:test

#5621 SLE15 stateless support
  xCAT-server/share/xcat/netboot/sle/compute.sle15.x86_64.exlist
  xCAT-server/share/xcat/netboot/sle/compute.sle15.x86_64.pkglist
  xCAT-server/share/xcat/netboot/sle/compute.sle15.x86_64.postinstall
  xCAT-server/share/xcat/netboot/sle/dracut_033/check
  xCAT-server/share/xcat/netboot/sle/dracut_033/install.netboot
  xCAT-server/share/xcat/netboot/sle/dracut_033/install.statelite
  xCAT-server/share/xcat/netboot/sle/dracut_033/installkernel
  xCAT-server/share/xcat/netboot/sle/dracut_033/patch/syslog/module-setup.sh
  xCAT-server/share/xcat/netboot/sle/dracut_033/patch/syslog/rsyslogd-start.sh
  xCAT-server/share/xcat/netboot/sle/dracut_033/patch/syslog/syslog-genrules.sh
  xCAT-server/share/xcat/netboot/sle/dracut_033/xcat-cmdline.sh
  xCAT-server/share/xcat/netboot/sle/dracut_033/xcat-premount.sh
  xCAT-server/share/xcat/netboot/sle/dracut_033/xcat-prepivot.sh
  xCAT-server/share/xcat/netboot/sle/dracut_033/xcatroot
  xCAT-server/share/xcat/netboot/sle/genimage
  xCAT-server/share/xcat/netboot/sle/geninitrd
  xCAT-server/share/xcat/netboot/sle/service.sle15.pkglist
  xCAT-server/share/xcat/netboot/sle/service.sle15.postinstall
  xCAT-server/share/xcat/netboot/sle/service.sle15.x86_64.otherpkgs.pkglist
  xCAT/postscripts/xcatpostinit.service
Labels: priority:low

#6486 Support SLE15 diskfull installation
  xCAT-server/share/xcat/install/scripts/post.sle
  xCAT-server/share/xcat/install/scripts/pre.sle
  xCAT-server/share/xcat/install/sle/compute.pkglist
  xCAT-server/share/xcat/install/sle/compute.sle15.pkglist
  xCAT-server/share/xcat/install/sle/compute.sle15.tmpl
  xCAT-server/share/xcat/install/sle/compute.tmpl
Labels: component:os_provision, component:xcatd

#6487 New regression bundle for kits
  xCAT-test/autotest/bundle/rhels_kits.bundle
Labels: component:test

#6488 Remove /install/autoinst config files as part of nodepurge
  docs/source/guides/admin-guides/references/man1/nodepurge.1.rst
  xCAT-client/pods/man1/nodepurge.1.pod
  xCAT-server/lib/xcat/plugins/profilednodes.pm
Labels: component:obj_db_cmds

#6489 fixed three typos
  docs/source/advanced/sysclone/sysclone.rst
Labels: type:documentation

#6492 ... and the fourth typo of the same kind
  docs/source/advanced/sysclone/sysclone.rst
Labels: type:documentation

#6491 nodepurge testcases
  xCAT-test/autotest/bundle/MN_basic.bundle
  xCAT-test/autotest/bundle/rhels_ppc_daily.bundle
  xCAT-test/autotest/bundle/rhels_ppcle_daily.bundle
  xCAT-test/autotest/bundle/rhels_x86_daily.bundle
  xCAT-test/autotest/bundle/sles_ppc_daily.bundle
  xCAT-test/autotest/bundle/sles_ppcle_daily.bundle
  xCAT-test/autotest/bundle/sles_x86_daily.bundle
  xCAT-test/autotest/bundle/ubuntu_ppcle_daily.bundle
  xCAT-test/autotest/bundle/ubuntu_x86_daily.bundle
  xCAT-test/autotest/testcase/nodepurge/cases0
Labels: test:testcase_added

#6493 Add support to provision SLE15 diskfull/diskless compute nodes
  xCAT-server/share/xcat/install/sle/compute.pkglist
  xCAT-server/share/xcat/install/sle/compute.tmpl
  xCAT-server/share/xcat/install/sles/compute.sle15.pkglist
  xCAT-server/share/xcat/install/sles/compute.sle15.tmpl
  xCAT-server/share/xcat/install/sles/service.sle15.pkglist
  xCAT-server/share/xcat/install/sles/service.sle15.ppc64le.otherpkgs.pkglist
  xCAT-server/share/xcat/install/sles/service.sle15.tmpl
  xCAT-server/share/xcat/install/sles/service.sle15.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/sle/dracut_033/check
  xCAT-server/share/xcat/netboot/sle/dracut_033/install.netboot
  xCAT-server/share/xcat/netboot/sle/dracut_033/install.statelite
  xCAT-server/share/xcat/netboot/sle/dracut_033/installkernel
  xCAT-server/share/xcat/netboot/sle/dracut_033/patch/syslog/module-setup.sh
  xCAT-server/share/xcat/netboot/sle/dracut_033/patch/syslog/rsyslogd-start.sh
  xCAT-server/share/xcat/netboot/sle/dracut_033/patch/syslog/syslog-genrules.sh
  xCAT-server/share/xcat/netboot/sle/dracut_033/xcat-cmdline.sh
  xCAT-server/share/xcat/netboot/sle/dracut_033/xcat-premount.sh
  xCAT-server/share/xcat/netboot/sle/dracut_033/xcat-prepivot.sh
  xCAT-server/share/xcat/netboot/sle/dracut_033/xcatroot
  xCAT-server/share/xcat/netboot/sle/genimage
  xCAT-server/share/xcat/netboot/sle/geninitrd
  xCAT-server/share/xcat/netboot/sles/compute.sle15.exlist
  xCAT-server/share/xcat/netboot/sles/compute.sle15.pkglist
  xCAT-server/share/xcat/netboot/sles/compute.sle15.postinstall
  xCAT-server/share/xcat/netboot/sles/compute.sle15.x86_64.pkglist
  xCAT-server/share/xcat/netboot/sles/dracut_033/install.netboot
  xCAT-server/share/xcat/netboot/sles/dracut_033/install.statelite
  xCAT-server/share/xcat/netboot/sles/genimage
  xCAT-server/share/xcat/netboot/sles/service.sle15.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/sles/service.sle15.pkglist
  xCAT-server/share/xcat/netboot/sles/service.sle15.postinstall
  xCAT-server/share/xcat/netboot/sles/service.sle15.x86_64.otherpkgs.pkglist
Labels: component:os_provision, type:support

#6496 nodepurge test cases failed on the regression
  xCAT-test/autotest/testcase/nodepurge/cases0
Labels: component:automation, component:test, type:bug

#6497 Regression test failed on the nodeset_shell_incorrectmasterip
  xCAT-test/autotest/testcase/genesis/test.sh
Labels: component:automation, component:test
