Repository xcat2/xcat-core, pull requests merged in 2019-09, with the labels that each got.

#6416 Health check xcat-dep files before building tar and remove AIX support
  builddep.sh
Labels: component:packaging

#6420 Make xcat-dep tar file readable by all
  builddep.sh
Labels: component:packaging

#6428 Handle the bad return code if rinstall is failed on nodeset
  xCAT-server/lib/xcat/plugins/rinstall.pm
Labels: component:os_provision, component:xcatd

#6425 Openbmc hardware control with OP940 firmware
  xCAT-server/lib/perl/xCAT/OPENBMC.pm
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:hw_control, component:openbmc

#6427 Ubuntu dependency build
  build-ubunturepo
Labels: component:automation, component:packaging

#6429 Remove snapshot build info from docs
  docs/source/guides/install-guides/common_sections.rst
Labels: type:documentation

#6435 Remove old debug statements
  xCAT-server/lib/xcat/plugins/kvm.pm
Labels: component:virtualization
