Repository xcat2/xcat-core, pull requests merged in 2019-03, with the labels that each got.

#6041 [RH8] RHEL 8 Service node automatic installation
  docs/source/advanced/hierarchy/databases/postgres_configure.rst
  xCAT-server/share/xcat/install/rh/service.rhels8.pkglist
  xCAT-server/share/xcat/netboot/rh/service.rhels8.ppc64le.pkglist
  xCAT-server/share/xcat/netboot/rh/service.rhels8.x86_64.pkglist
  xCATsn/xCATsn.spec
Labels: sprint3

#6050 fix rspconfig error that no executor folder
  xCAT-openbmc-py/lib/python/agent/xcatagent/openbmc.py
Labels: component:openbmc

#6056 Revert "Update xCAT-server.spec to require a new version of grub2-xcat"
  xCAT-server/xCAT-server.spec
Labels: sprint4

#6059 recommend to use confignetwork in confignics docs
  docs/source/guides/admin-guides/manage_clusters/common/deployment/network/cfg_second_adapter.rst
Labels: sprint4

#6061 Set the default value of site.xcatsslversion to SSLv23:!SSLv2:!SSLv3:!TLSv1
  xCAT-server/sbin/xcatconfig
  xCAT-server/sbin/xcatd
Labels: sprint4

#6070 [RH8] Add --releasever argument to yum command
  xCAT-server/share/xcat/netboot/rh/genimage
Labels: sprint4

#6060 Modify openbmc python code to support python3
  xCAT-openbmc-py/lib/python/agent/client.py
  xCAT-openbmc-py/lib/python/agent/common/rest.py
  xCAT-openbmc-py/lib/python/agent/common/task.py
  xCAT-openbmc-py/lib/python/agent/common/utils.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc/openbmc_bmcconfig.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc/openbmc_eventlog.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc/openbmc_flash.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc/openbmc_inventory.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
  xCAT-openbmc-py/lib/python/agent/xcatagent/server.py
Labels: component:openbmc

#6078 Change the default_md in openssl.cnf.tmpl to sha384
  xCAT-server/share/xcat/ca/openssl.cnf.tmpl
Labels: sprint4

#6080 Merge `master` branch to `rhels8` branch
  .mailmap
  docs/source/guides/admin-guides/manage_clusters/common/deployment/network/cfg_second_adapter.rst
  xCAT-openbmc-py/lib/python/agent/client.py
  xCAT-openbmc-py/lib/python/agent/common/rest.py
  xCAT-openbmc-py/lib/python/agent/common/task.py
  xCAT-openbmc-py/lib/python/agent/common/utils.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc/openbmc_bmcconfig.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc/openbmc_eventlog.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc/openbmc_flash.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc/openbmc_inventory.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
  xCAT-openbmc-py/lib/python/agent/xcatagent/openbmc.py
  xCAT-openbmc-py/lib/python/agent/xcatagent/server.py
  xCAT-probe/xCAT-probe.spec
  xCAT-server/lib/xcat/plugins/onie.pm
  xCAT-test/autotest/bundle/sles_ppcle_daily.bundle
  xCAT-test/autotest/testcase/nodeset/cases0
Labels: sprint4

#6081 Handle the exit code properly when `copycds` failed, and pass through outputs of `cpio`
  xCAT-server/lib/xcat/plugins/anaconda.pm
Labels: sprint4

#6082 Merge master branch to rhels8 branch
  xCAT-server/lib/xcat/plugins/anaconda.pm
Labels: sprint4

#5825 Update the switch based switch discovery documentation
  docs/source/advanced/networks/switchdiscover/switch_based_switch_discovery.rst
Labels: type:documentation

#6054 add 15-minute quick start doc
  docs/source/guides/get-started/index.rst
  docs/source/guides/get-started/quick_start.rst
  docs/source/guides/get-started/workflow_guide.rst
  docs/source/index.rst
  docs/source/overview/index.rst
Labels: type:documentation

#6066 confignetwork framework refine using nmcli
  xCAT/postscripts/confignetwork
  xCAT/postscripts/nicutils.sh
Labels: component:network, sprint4

#6090 [RH8] Show warning message when site.xcatsslversion has an value during upgrade
  docs/source/advanced/security/ssl_config.rst
  docs/source/guides/admin-guides/references/man5/site.5.rst
  xCAT-server/sbin/xcatconfig
Labels: sprint4

#6084 Some more doc fixes
  docs/source/guides/admin-guides/manage_clusters/common/deployment/syncfile/syncfile_synclist_file.rst
  docs/source/guides/admin-guides/references/man1/updatenode.1.rst
  docs/source/guides/admin-guides/references/man1/xdcp.1.rst
  docs/source/guides/admin-guides/references/man5/site.5.rst
  xCAT-client/pods/man1/updatenode.1.pod
  xCAT-client/pods/man1/xdcp.1.pod
  xCAT-server/lib/xcat/plugins/DBobjectdefs.pm
Labels: type:documentation

#6095 [RH8] Revise xcatconfig, show warning message if `TLSv1' is used
  xCAT-server/sbin/xcatconfig
Labels: sprint4

#6097 fix issue syntax error in xcatdsklspost
  xCAT/postscripts/xcatdsklspost
Labels: component:postscripts

#6098 Do not show error message when command failure
  perl-xCAT/xCAT/Utils.pm
Labels: sprint4

#6099 Merge master branch to rhels8 branch
  docs/source/advanced/networks/switchdiscover/switch_based_switch_discovery.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/syncfile/syncfile_synclist_file.rst
  docs/source/guides/admin-guides/references/man1/updatenode.1.rst
  docs/source/guides/admin-guides/references/man1/xdcp.1.rst
  docs/source/guides/admin-guides/references/man5/site.5.rst
  docs/source/guides/get-started/index.rst
  docs/source/guides/get-started/quick_start.rst
  docs/source/guides/get-started/workflow_guide.rst
  docs/source/index.rst
  docs/source/overview/index.rst
  xCAT-client/pods/man1/updatenode.1.pod
  xCAT-client/pods/man1/xdcp.1.pod
  xCAT-server/lib/xcat/plugins/DBobjectdefs.pm
  xCAT-test/autotest/testcase/xcatconfig/case0
  xCAT/postscripts/confignetwork
  xCAT/postscripts/nicutils.sh
  xCAT/postscripts/xcatdsklspost
Labels: sprint4

#6101 [RH8] Revise Schema.pm based on the new default setting of xcatsslversion
  perl-xCAT/xCAT/Schema.pm
Labels: sprint4

#6102 Enlarge the default size of the root filesystem for RHEL 8
  xCAT-server/share/xcat/install/scripts/pre.rhels8
Labels: sprint4

#6105 Revert "[RH8] Revise xcatconfig, show warning message if `TLSv1' is used"
  xCAT-server/sbin/xcatconfig
Labels: sprint4

#6106 add common functions for confignetwork using nmcli
  xCAT/postscripts/confignetwork
  xCAT/postscripts/nicutils.sh
  xCAT/postscripts/xcatlib.sh
Labels: sprint4

#6112 fix issue 6111, make args passed into be string
  xCAT-openbmc-py/lib/python/agent/xcatagent/server.py
Labels: component:openbmc

#6110 configvlan with nmcli
  xCAT/postscripts/confignetwork
  xCAT/postscripts/nicutils.sh
Labels: component:network

#6117 Add python3 to the default pkglist for RHEL 8
  xCAT-server/share/xcat/install/rh/compute.rhels8.pkglist
  xCAT-server/share/xcat/install/rh/service.rhels8.pkglist
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.ppc64le.pkglist
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.x86_64.pkglist
  xCAT-server/share/xcat/netboot/rh/service.rhels8.ppc64le.pkglist
  xCAT-server/share/xcat/netboot/rh/service.rhels8.x86_64.pkglist
Labels: sprint4

#6113 confignetwork configure bridge using nmcli
  xCAT/postscripts/confignetwork
  xCAT/postscripts/nicutils.sh
Labels: component:network, sprint4

#6120 fix issue Need to enter passphrase when install redhat 6.10 on x86_84 #6119
  xCAT/postscripts/remoteshell
Labels: sprint4

#6121 Make xCAT statelite compute node working on RHEL 8
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.localdisk
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite
Labels: sprint4

#6040 Revise test case xdcp_nonroot_user.
  xCAT-test/autotest/testcase/xdcp/cases1
Labels: sprint3

#6123 move the stop label from makedhcp_remote_network case
  xCAT-test/autotest/testcase/makedhcp/cases0
Labels: component:test

#6128 replace check brctl position since there is no bridge-utils RH8
  xCAT/postscripts/confignetwork
Labels: component:network

#6134 Fix RHEL 8 diskless service node
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.ppc64le.pkglist
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.x86_64.pkglist
  xCAT-server/share/xcat/netboot/rh/service.rhels8.ppc64le.pkglist
  xCAT-server/share/xcat/netboot/rh/service.rhels8.x86_64.pkglist
  xCAT/postscripts/servicenode
Labels: sprint4

#6137 Fix python error, TypeError: cannot use a string pattern on a bytes-like object
  xCAT-server/share/xcat/install/scripts/pre.rhels8
Labels: sprint4

#6139 fix configeth using nmcli connection name with space
  xCAT/postscripts/configeth
Labels: component:network

#6144 Partly revert "Revise openssl settings for RHEL 8 (#5967)"
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.localdisk
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite.ppc.redhat
  xCAT/postscripts/getcredentials.awk
  xCAT/postscripts/getpostscript.awk
  xCAT/postscripts/startsyncfiles
  xCAT/postscripts/startsyncfiles.awk
Labels: sprint4

#6149 Fix python error, TabError: inconsistent use of tabs and spaces in indentation
  xCAT-server/lib/perl/xCAT/Template.pm
  xCAT-server/share/xcat/install/scripts/pre.rhels8
Labels: sprint4

#6147 spec file not be used for xCAT-openbmc-py3 build
  xCAT-openbmc-py/xCAT-openbmc-py3.build
Labels: component:openbmc, component:packaging

#6153 enhance configure bond and bridge 2 test cases
  xCAT-test/autotest/testcase/confignetwork/cases0
  xCAT/postscripts/configeth
Labels: component:network

#6154 Update configvlan case
  xCAT-test/autotest/testcase/confignetwork/cases0
Labels: component:network, component:test

#6138 configure bond support using nmcli
  xCAT/postscripts/confignetwork
  xCAT/postscripts/nicutils.sh
Labels: component:network

#6156 Remove option -no-host-reboot for rflash
  docs/source/guides/admin-guides/manage_clusters/ppc64le/management/advanced/rflash/openbmc/openbmc_common.rst
  perl-xCAT/xCAT/Usage.pm
  xCAT-client/pods/man1/rflash.1.pod
Labels: component:openbmc, sprint4

#6165 refine configeth using nmcli
  xCAT-test/autotest/testcase/confignetwork/cases0
  xCAT/postscripts/configeth
  xCAT/postscripts/confignetwork
Labels: sprint4

#6052 add physical machine test bundle
  xCAT-test/autotest/bundle/physical_node_openpower_ipmi.bundle
  xCAT-test/autotest/bundle/physical_node_openpower_openbmc_perl.bundle
  xCAT-test/autotest/bundle/physical_node_openpower_openbmc_python.bundle
  xCAT-test/autotest/bundle/physical_node_power_hmc.bundle
  xCAT-test/autotest/bundle/physical_node_x86_ipmi.bundle
Labels: component:test

#6170 refine confignetwork 4 basic test cases support nmcli
  xCAT-test/autotest/testcase/confignetwork/cases0
Labels: component:test

#6168 add autoconnect-priority for xCAT nmcli con and fix RH7.6 failure
  xCAT/postscripts/configeth
  xCAT/postscripts/confignetwork
  xCAT/postscripts/nicutils.sh
Labels: component:network

#6179 add wicked check in confignetwork for sles
  xCAT/postscripts/configeth
  xCAT/postscripts/confignetwork
  xCAT/postscripts/nicutils.sh
Labels: component:network

#6183 support python3 update exceptions function code
  xCAT-openbmc-py/lib/python/agent/common/exceptions.py
Labels: component:openbmc

#6181 update makeconservercf cases
  xCAT-test/autotest/testcase/makeconservercf/cases0
Labels: component:test

#6182 Fix case problem for rflash_h
  xCAT-test/autotest/testcase/rflash/rflash_openbmc.0
Labels: component:test

#6185 Update release information for 2.14.6 release
  docs/source/conf.py
  docs/source/overview/xcat2_release.rst
Labels: sprint1, type:documentation

#6190 update daily bundle to remove makeconservercf cases
  xCAT-test/autotest/bundle/rhels_ppc_daily.bundle
  xCAT-test/autotest/bundle/rhels_ppcle_daily.bundle
  xCAT-test/autotest/bundle/rhels_x86_daily.bundle
  xCAT-test/autotest/bundle/sles_ppc_daily.bundle
  xCAT-test/autotest/bundle/sles_ppcle_daily.bundle
  xCAT-test/autotest/bundle/sles_x86_daily.bundle
  xCAT-test/autotest/bundle/ubuntu_ppcle_daily.bundle
  xCAT-test/autotest/bundle/ubuntu_x86_daily.bundle
Labels: component:test

#6187 stop conserver service in makeconservercf cases
  xCAT-test/autotest/testcase/makeconservercf/cases0
Labels: component:test

#6192 Merge master to 2.14 for 2.14.6 release(2)
  docs/source/guides/admin-guides/manage_clusters/common/deployment/enable_kdump.rst
  xCAT-test/autotest/bundle/rhels_ppc_daily.bundle
  xCAT-test/autotest/bundle/rhels_ppcle_daily.bundle
  xCAT-test/autotest/bundle/rhels_x86_daily.bundle
  xCAT-test/autotest/bundle/sles_ppc_daily.bundle
  xCAT-test/autotest/bundle/sles_ppcle_daily.bundle
  xCAT-test/autotest/bundle/sles_x86_daily.bundle
  xCAT-test/autotest/bundle/ubuntu_ppcle_daily.bundle
  xCAT-test/autotest/bundle/ubuntu_x86_daily.bundle
  xCAT-test/autotest/testcase/makeconservercf/cases0
  xCAT-test/autotest/testcase/packimg/cases0
  xCAT-test/autotest/testcase/passwd/case0
  xCAT-test/autotest/testcase/runcmdinstaller/cases0
  xCAT/postscripts/configeth
  xCAT/postscripts/enablekdump
Labels: component:automation

#6193 work around some RH version ip link state UNKNOWN issue
  xCAT/postscripts/configeth
Labels: component:network

#6195 Merge master to 2.14 branch for 2.14.6 release
  xCAT-test/autotest/testcase/kdump/linux_diskless_kdump
  xCAT/postscripts/configeth
Labels: component:automation
