Repository xcat2/xcat-core, pull requests merged in 2019-04, with the labels that each got.

#6196 Add more debug information to investigate why operating goconserver frequently will trigger problem
  xCAT-test/autotest/testcase/install_xCAT/case0
  xCAT-test/autotest/testcase/xcatconfig/case0
Labels: component:test

#6204 add hostname generation on compute node doc
  docs/source/advanced/domain_name_resolution/domain_name_resolution.rst
Labels: type:documentation

#6200 update go-xcat cases to support ubuntu18.04.x
  xCAT-test/autotest/testcase/go_xcat/case0
  xCAT-test/autotest/testcase/go_xcat/case1
  xCAT-test/autotest/testcase/go_xcat/case2
Labels: component:test

#6203 Handle openbmc login and rflash errors
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:openbmc

#6213 Add some more debugs to travis
  travis.pl
Labels: component:test

#6216 Verify packaging commands can be executed during genimage processing
  xCAT-server/share/xcat/netboot/sles/genimage
  xCAT-server/share/xcat/netboot/ubuntu/genimage
Labels: component:os_provision

#6211 Revise the pkglist files for RHEL 8 diskless compute node and service node
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.ppc64le.pkglist
  xCAT-server/share/xcat/netboot/rh/compute.rhels8.x86_64.pkglist
  xCAT-server/share/xcat/netboot/rh/service.rhels8.ppc64le.pkglist
  xCAT-server/share/xcat/netboot/rh/service.rhels8.x86_64.pkglist
Labels: sprint1

#6201 confignetwork extra params support and multiple ipv4 address ethernet nic support using nmcli
  xCAT/postscripts/configeth
  xCAT/postscripts/confignetwork
  xCAT/postscripts/nicutils.sh
Labels: component:network

#6214 configib support nmcli
  xCAT/postscripts/configib
  xCAT/postscripts/nicutils.sh
Labels: sprint1

#6225 Undo verify packaging command PR 6216
  xCAT-server/share/xcat/netboot/sles/genimage
  xCAT-server/share/xcat/netboot/ubuntu/genimage
Labels: component:os_provision

#6197 update case rspconfig_dump_download and rspconfig_dump_no_option
  xCAT-test/autotest/testcase/rspconfig/cases1
Labels: component:test

#6227 Only pass "--compress" argument to dracut when ($dracutver > "033")
  docs/source/guides/admin-guides/manage_clusters/common/deployment/acc_initrd_rootimg_gen.rst
  xCAT-server/share/xcat/netboot/rh/genimage
Labels: sprint2

#6209 Add server name to rspconfig dump output
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc/openbmc_bmcconfig.py
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:openbmc

#6237 fix issue 6229 based on customer suggestion
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc/openbmc_bmcconfig.py
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
Labels: component:openbmc

#6240 support https:// prefix in otherpkgdir and pkgdir; ignore invalid repos
  xCAT-server/share/xcat/netboot/rh/genimage
Labels: component:os_provision

#6219 A new partition scheme for RHEL 8
  xCAT-server/share/xcat/install/scripts/pre.rhels8
Labels: sprint2

#6087 add more debug information for dynamic group test cases
  xCAT-test/autotest/testcase/chdef/cases0
  xCAT-test/autotest/testcase/mkdef/cases0
  xCAT-test/autotest/testcase/rmdef/cases0
Labels: component:test, sprint1

#6244 [OpenBMC] fix reventlog for python2
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
Labels: component:openbmc, test:testcase_requested

#6251 Use xCAT Automatic Signing Key, 5619700D to do the signing
  builddep.sh
Labels: sprint2

#6243 Remove conserver-xcat from go-xcat package list
  xCAT-server/share/xcat/tools/go-xcat
Labels: sprint2

#6242 Remove conserver-xcat from all xCAT shipped RPM requirements
  xCAT-server/xCAT-server.spec
  xCAT/xCAT.spec
  xCATsn/xCATsn.spec
Labels: sprint2

#6248 enhance openbmc ntpservers output
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
Labels: component:openbmc

#6210 Remove some AIX references in docs
  docs/source/advanced/mixed_cluster/support_matrix.rst
  docs/source/overview/features.rst
  docs/source/overview/support_matrix.rst
Labels: type:documentation

#6220 Update the two README files in the xcat-core project
  README.md
  README.rst
  docs/README.md
Labels: type:documentation

#6255 Remove package conserver-xcat from service node otherpkgs package lists
  xCAT-server/share/xcat/install/rh/service.rhels7.ppc64.otherpkgs.pkglist
  xCAT-server/share/xcat/install/rh/service.rhels7.ppc64le.otherpkgs.pkglist
  xCAT-server/share/xcat/install/rh/service.rhels7.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/install/sles/service.sles12.ppc64le.otherpkgs.pkglist
  xCAT-server/share/xcat/install/sles/service.sles12.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/rh/service.rhels7.ppc64le.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/rh/service.rhels7.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/sles/service.sles12.ppc64le.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/sles/service.sles12.x86_64.otherpkgs.pkglist
Labels: sprint2

#6252 change /var/named permission to default 0750 in makedns
  xCAT-server/lib/xcat/plugins/ddns.pm
Labels: component:dns

#6222 Add documentation in RTD for how to use an xCAT docker image
  docs/source/advanced/docker/docker_registry.rst
  docs/source/advanced/docker/dockerized_xcat/dockerized_xcat.rst
  docs/source/advanced/docker/dockerized_xcat/run_xcat_in_docker_compose.rst
  docs/source/advanced/docker/dockerized_xcat/run_xcat_in_docker_host.rst
  docs/source/advanced/docker/dockerized_xcat/run_xcat_in_docker_native.rst
  docs/source/advanced/docker/dockerized_xcat/setup_docker_host.rst
  docs/source/advanced/docker/index.rst
  docs/source/advanced/docker/lifecycle_management.rst
Labels: type:documentation

#6257 Let makentp fall back to use ntpd when systemctl is not available.
  xCAT-server/lib/xcat/plugins/makentp.pm
  xCAT/postscripts/setupntp
Labels: sprint2

#6259 Add goconserver to the SLES12 otherpkgs.pkglist. In order to pull the xcat-dep directory into the zypper repository
  xCAT-server/share/xcat/install/sles/service.sles12.ppc64le.otherpkgs.pkglist
  xCAT-server/share/xcat/install/sles/service.sles12.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/sles/service.sles12.ppc64le.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/sles/service.sles12.x86_64.otherpkgs.pkglist
Labels: sprint2

#6260 update typo and add one reminder for xcat docker container document
  docs/source/advanced/docker/dockerized_xcat/run_xcat_in_docker_host.rst
Labels: component:docker, sprint2, type:documentation

#6232 update test cases to apply in xcat docker container
  xCAT-test/autotest/testcase/makedns/cases0
  xCAT-test/autotest/testcase/makehosts/cases0
  xCAT-test/autotest/testcase/nodeset/cases0
  xCAT-test/autotest/testcase/passwd/case0
  xCAT-test/autotest/testcase/psh/cases0
Labels: component:test

#6262 update case to apply in container
  xCAT-test/autotest/testcase/kdump/linux_diskless_kdump
Labels: component:test

#6265 Add notice of nfs setting in xcat docker container document
  docs/source/advanced/docker/dockerized_xcat/run_xcat_in_docker_host.rst
Labels: component:docker, sprint2, type:documentation

#6234 Add DB pkgs check on SN for xcatprobe xcatmn
  xCAT-probe/subcmds/xcatmn
Labels: component:xcatprobe

#6263 Update kit cases to apply in xcat container
  xCAT-test/autotest/testcase/addkitcomp/case0
  xCAT-test/autotest/testcase/chkkitcomp/cases0
  xCAT-test/autotest/testcase/rmkit/case0
Labels: component:test
