Repository xcat2/xcat-core, pull requests merged in 2020-01, with the labels that each got.

#6520 Improve OpenBMC reventlog message for missing policyTable.json
  xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:openbmc, type:usability

#6522 Change shabang for python on rhels8.1
  xCAT-test/autotest/testcase/xcat_inventory/validatehelper
Labels: component:test, rh8

#6521 Default to all for OpenBMC reventlog verbose
  xCAT-server/lib/xcat/plugins/openbmc2.pm
Labels: component:openbmc

#6528 Add net-tools-deprecated package to SLE15 package list
  xCAT-server/share/xcat/install/sles/compute.sle15.pkglist
  xCAT-server/share/xcat/install/sles/service.sle15.pkglist
  xCAT-server/share/xcat/netboot/sles/compute.sle15.pkglist
  xCAT-server/share/xcat/netboot/sles/compute.sle15.x86_64.pkglist
  xCAT-server/share/xcat/netboot/sles/service.sle15.pkglist
Labels: component:packaging

#6529 Deprecate nodechmac command
  docs/source/guides/admin-guides/references/man1/nodechmac.1.rst
  xCAT-client/pods/man1/nodechmac.1.pod
Labels: type:documentation

#6530 Fix service.sle15.tmpl
  xCAT-server/share/xcat/install/sles/service.sle15.tmpl
Labels: component:hierarchy, component:os_provision

#6531 Display VM disk purge message instead of just logging it
  docs/source/guides/admin-guides/references/man1/rmvm.1.rst
  xCAT-client/pods/man1/rmvm.1.pod
  xCAT-server/lib/xcat/plugins/kvm.pm
Labels: component:virtualization, type:documentation

#6524 bmcdiscover with bmc password expiration
  docs/source/guides/admin-guides/references/man1/bmcdiscover.1.rst
  xCAT-client/pods/man1/bmcdiscover.1.pod
  xCAT-server/lib/xcat/plugins/bmcdiscover.pm
Labels: component:openbmc, type:documentation

#6535 Update test script to print more debug info
  xCAT-test/autotest/testcase/genesis/test.sh
Labels: component:test

#6536 Add SLE15 Hierarchy support for ppc64le
  xCAT-server/lib/xcat/plugins/dhcp.pm
  xCAT-server/share/xcat/install/sles/compute.sle15.pkglist
  xCAT-server/share/xcat/install/sles/service.sle15.pkglist
  xCAT-server/share/xcat/install/sles/service.sle15.ppc64le.otherpkgs.pkglist
  xCAT-server/share/xcat/install/sles/service.sle15.tmpl
  xCAT-server/share/xcat/netboot/sles/compute.sle15.pkglist
  xCAT-server/share/xcat/netboot/sles/compute.sle15.x86_64.pkglist
  xCAT-server/share/xcat/netboot/sles/service.sle15.pkglist
  xCAT/postscripts/otherpkgs
  xCAT/postscripts/syslog
Labels: cluster_setup, component:dhcp, component:hierarchy, component:os_provision

#6537 Support otherpkgs as postbootscript for SLE15
  xCAT-server/share/xcat/install/scripts/post.xcat
  xCAT/postscripts/enablekdump
  xCAT/postscripts/setupntp.traditional
Labels: component:hierarchy

#6540 SLE15: Merge some stuff from Lenovo branch
  xCAT-server/lib/xcat/plugins/sles.pm
  xCAT-server/share/xcat/install/sles/compute.sle15.tmpl
  xCAT-server/share/xcat/install/sles/compute.sles12.tmpl
  xCAT-server/share/xcat/install/sles/service.sle15.tmpl
  xCAT-server/share/xcat/install/sles/service.sles12.tmpl
Labels: component:os_provision

#6538 SLE15: genimage fixes
  xCAT-server/share/xcat/netboot/sles/compute.sle15.x86_64.pkglist
  xCAT-server/share/xcat/netboot/sles/dracut_033/xcat-prepivot.sh
  xCAT-server/share/xcat/netboot/sles/dracut_033/xcatroot
  xCAT-server/share/xcat/netboot/sles/genimage
Labels: cluster_setup, component:os_provision

#6542 linux_diskless_kdump testcase enhancement2
  xCAT-test/autotest/testcase/kdump/linux_diskless_kdump
Labels: component:test

#6545 Add more output to runcmdinstaller_command testcase
  xCAT-test/autotest/testcase/runcmdinstaller/cases0
Labels: component:test

#6546 Failed to run otherpkgs for rhel8.1.0 service node
  xCAT/postscripts/ospkgs
  xCAT/postscripts/otherpkgs
Labels: component:os_provision

#6548 RPM permission verify
  builddep.sh
Labels: component:packaging

#6550 [FVT]Missing tftpserver and xcatmaster for the testnode
  xCAT-test/autotest/testcase/genesis/test.sh
Labels: component:test

#6552 OpenBMC rvitals command to handle variable number of fans
  docs/source/guides/admin-guides/manage_clusters/common/parallel_cmd.rst
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:openbmc
