Repository xcat2/xcat-core, pull requests merged in 2020-08, with the labels that each got.

#6794 Remove the extra double quote of the rm command.
  xCAT-test/autotest/testcase/installation/compare_postscripts
Labels: component:test

#6764 xdsh related documentation updates
  docs/source/guides/admin-guides/references/man1/updatenode.1.rst
  docs/source/guides/admin-guides/references/man1/xdsh.1.rst
  docs/source/guides/admin-guides/references/man1/xdshbak.1.rst
  docs/source/guides/admin-guides/references/man1/xdshcoll.1.rst
  xCAT-client/pods/man1/updatenode.1.pod
  xCAT-client/pods/man1/xdsh.1.pod
  xCAT-client/pods/man1/xdshbak.1.pod
  xCAT-client/pods/man1/xdshcoll.1.pod
Labels: type:documentation

#6768 Replace misspelled gpgpcheck with gpgcheck
  xCAT-server/share/xcat/netboot/debian/genimage
  xCAT-server/share/xcat/netboot/fedora12/genimage
  xCAT-server/share/xcat/netboot/fedora12/geninitrd
  xCAT-server/share/xcat/netboot/mic/genimage
  xCAT-server/share/xcat/netboot/rh/genimage
  xCAT-server/share/xcat/netboot/rh/genimage.rh4
  xCAT-server/share/xcat/netboot/sles/genimage.yum
Labels: component:os_provision

#6796 On RHEL8 do not use vers=3 when mounting kdump filesystem
  xCAT/postscripts/enablekdump
Labels: component:postscripts

#6780 Change the regex in post.xcat.ng to accommodate long file names
  xCAT-server/share/xcat/install/scripts/post.xcat.ng
Labels: component:postscripts

#6795 Fix usage and example for replaycons command
  docs/source/guides/admin-guides/references/man1/replaycons.1.rst
  xCAT-client/pods/man1/replaycons.1.pod
  xCAT-server/bin/replaycons
Labels: type:documentation

#6788 Generate local repository template if not exist or empty
  xCAT-server/lib/xcat/plugins/anaconda.pm
Labels: component:os_provision, component:postscripts, component:xcatd

#6709 test: confignetwork: update regexp to fix IP matching
  xCAT-test/autotest/testcase/confignetwork/cases0
Labels: component:test

#6803 Retry rinstall if first one fails
  xCAT-test/autotest/testcase/commoncmd/retry_install.sh
Labels: component:test

#6805 Add kernel-modules-extra to dracut module list
  xCAT-server/share/xcat/netboot/rh/genimage
Labels: component:infiniband

#6806 Verify if kernel-modules-extra exists before adding
  xCAT-server/share/xcat/netboot/rh/genimage
Labels: component:infiniband

#6807 xcat-inventory backend testcase fix
  xCAT-test/autotest/testcase/xcat_inventory/cases.backend
Labels: component:test

#6800 Remove depricated Perl usage of keys on scalar
  xCAT-server/xCAT-wsapi/xcatws.cgi
Labels: component:restapi

#6798 Added enabling nv_rsync service in cuda11_power9_setup postscripts
  xCAT-server/share/xcat/samples/cuda11/cuda11_power9_setup
Labels: component:postscripts

#6762 Update pgsqlsetup command and related docs
  docs/source/advanced/hierarchy/databases/postgres_remove.rst
  docs/source/guides/admin-guides/references/man1/pgsqlsetup.1.rst
  xCAT-client/bin/pgsqlsetup
  xCAT-client/pods/man1/pgsqlsetup.1.pod
Labels: component:database, type:documentation

#6810 Better testcase output when makedhcp -q fails
  xCAT-test/autotest/testcase/installation/reg_linux_diskless_installation_flat
Labels: component:test
