Repository xcat2/xcat-core, pull requests merged in 2021-04, with the labels that each got.

#6932 SLES15.2 service node pkglist needs wget
  xCAT-server/share/xcat/install/sles/service.sle15.pkglist
  xCAT-server/share/xcat/netboot/sles/genimage
Labels: component:os_provision

#6935 Use correct zypper flag --auto-agree-with-licenses
  xCAT/postscripts/otherpkgs
Labels: component:os_provision, component:postscripts

#6936 Use correct Perl string compare operator
  xCAT-client/bin/mysqlsetup
  xCAT-probe/subcmds/xcatmn
  xCAT-server/lib/xcat/plugins/openbmc.pm
Labels: component:database, component:openbmc, component:xcatprobe

#6938 Remove sp1flag from mysqlsetup
  xCAT-client/bin/mysqlsetup
Labels: component:database

#6939 Make xCAT-server require httpd
  xCAT-server/xCAT-server.spec
Labels: component:packaging

#6930 xcatprobe fixes
  xCAT-probe/subcmds/xcatmn
Labels: component:xcatprobe

#6937 Move to bionic release for Travis
  .travis.yml
  travis.pl
Labels: component:CI

#6919 Support for Oracle Linux 7 and Oracle Linux 8
  perl-xCAT/xCAT/data/discinfo.pm
  xCAT-server/lib/perl/xCAT/Template.pm
  xCAT-server/share/xcat/install/ol/compute.ol7.pkglist
  xCAT-server/share/xcat/install/ol/compute.ol7.tmpl
  xCAT-server/share/xcat/install/ol/compute.ol8.pkglist
  xCAT-server/share/xcat/install/ol/compute.ol8.tmpl
  xCAT-server/share/xcat/netboot/ol/compute.ol7.x86_64.exlist
  xCAT-server/share/xcat/netboot/ol/compute.ol7.x86_64.pkglist
  xCAT-server/share/xcat/netboot/ol/compute.ol7.x86_64.postinstall
  xCAT-server/share/xcat/netboot/ol/compute.ol8.x86_64.exlist
  xCAT-server/share/xcat/netboot/ol/compute.ol8.x86_64.pkglist
  xCAT-server/share/xcat/netboot/ol/compute.ol8.x86_64.postinstall
  xCAT-server/share/xcat/netboot/ol/dracut_047
  xCAT-server/share/xcat/netboot/ol/geninitrd
  xCAT-server/share/xcat/netboot/rh/genimage
Labels: component:os_provision

#6949 Shorten provision wait time
  xCAT-test/autotest/testcase/commoncmd/retry_install.sh
Labels: component:test

#6948 Support Oracle Linux on service nodes
  perl-xCAT/xCAT/data/discinfo.pm
  xCAT-server/lib/xcat/plugins/anaconda.pm
  xCAT-server/share/xcat/install/ol/service.ol7.tmpl
  xCAT-server/share/xcat/install/ol/service.ol7.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/install/ol/service.ol7.x86_64.pkglist
  xCAT-server/share/xcat/install/ol/service.ol8.pkglist
  xCAT-server/share/xcat/install/ol/service.ol8.ppc64le.otherpkgs.pkglist
  xCAT-server/share/xcat/install/ol/service.ol8.tmpl
  xCAT-server/share/xcat/install/ol/service.ol8.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/ol/service.ol7.x86_64.exlist
  xCAT-server/share/xcat/netboot/ol/service.ol7.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/ol/service.ol7.x86_64.pkglist
  xCAT-server/share/xcat/netboot/ol/service.ol7.x86_64.postinstall
  xCAT-server/share/xcat/netboot/ol/service.ol8.x86_64.exlist
  xCAT-server/share/xcat/netboot/ol/service.ol8.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/ol/service.ol8.x86_64.pkglist
  xCAT-server/share/xcat/netboot/ol/service.ol8.x86_64.postinstall
Labels: component:os_provision

#6954 Improve verification of prsync command in testcases
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_hierarchy_by_nfs
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_hierarchy_by_ramdisk
Labels: component:test

#6953 Improve xcatprobe check for firewall
  xCAT-probe/lib/perl/probe_utils.pm
Labels: component:xcatprobe

#6955 Fix testcase command and operator for prsync
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_hierarchy_by_nfs
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_hierarchy_by_ramdisk
Labels: component:test

#6956 Increase regression test cluster VM service node disk
  xCAT-test/autotest/testcase/installation/setup_vm
Labels: component:test

#6958 Add missing shebangs to key scripts
  xCAT-server/share/xcat/scripts/setup-server-cert.sh
  xCAT-server/share/xcat/scripts/setup-xcat-ca.sh
Labels: type:usability

#6959 Fix mistake where someone used ext4
  xCAT-server/share/xcat/install/scripts/pre.rhels8
Labels: component:os_provision

#6960 Modify test case makentp_extntpserver_value and add it to seven daily bundles
  xCAT-test/autotest/bundle/rhels_ppc_daily.bundle
  xCAT-test/autotest/bundle/rhels_ppcle_daily.bundle
  xCAT-test/autotest/bundle/rhels_x86_daily.bundle
  xCAT-test/autotest/bundle/sles_ppcle_daily.bundle
  xCAT-test/autotest/bundle/sles_x86_daily.bundle
  xCAT-test/autotest/bundle/ubuntu_ppcle_daily.bundle
  xCAT-test/autotest/bundle/ubuntu_x86_daily.bundle
  xCAT-test/autotest/testcase/makentp/cases0
Labels: component:test
