Repository xcat2/xcat-core, pull requests merged in 2021-09, with the labels that each got.

#7023 Update kernel options to disable selinux on OL and Rocky
  xCAT-server/lib/xcat/plugins/anaconda.pm
Labels: component:security

#7022 Enhance reg_linux_diskless_installation_flat for testing VM machine types
  xCAT-test/autotest/testcase/installation/reg_linux_diskless_installation_flat
Labels: test:testcase_added

#7024 Update genesis-base building instructions
  docs/source/references/coral/known_issues/genesis_base.rst
Labels: type:documentation

#7025 Support VM machine types specified through vm.othersettings
  docs/source/guides/admin-guides/references/man5/vm.5.rst
  docs/source/guides/admin-guides/references/man7/group.7.rst
  docs/source/guides/admin-guides/references/man7/node.7.rst
  perl-xCAT/xCAT/Schema.pm
  xCAT-server/lib/xcat/plugins/kvm.pm
Labels: type:documentation, component:virtualization

#7035 Test KVM machine types in reg_linux_diskless_installation_flat by KVM clusters only
  xCAT-test/autotest/testcase/installation/reg_linux_diskless_installation_flat
Labels: component:virtualization, component:test

#7029 Support CentOS8 Stream
  xCAT-server/lib/xcat/plugins/anaconda.pm
  xCAT-server/share/xcat/install/centos/compute.centos-stream8.pkglist
  xCAT-server/share/xcat/install/centos/compute.centos-stream8.tmpl
  xCAT-server/share/xcat/install/centos/service.centos-stream8.pkglist
  xCAT-server/share/xcat/install/centos/service.centos-stream8.ppc64le.otherpkgs.pkglist
  xCAT-server/share/xcat/install/centos/service.centos-stream8.tmpl
  xCAT-server/share/xcat/install/centos/service.centos-stream8.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/centos/compute.centos-stream8.ppc64le.exlist
  xCAT-server/share/xcat/netboot/centos/compute.centos-stream8.ppc64le.pkglist
  xCAT-server/share/xcat/netboot/centos/compute.centos-stream8.ppc64le.postinstall
  xCAT-server/share/xcat/netboot/centos/compute.centos-stream8.x86_64.exlist
  xCAT-server/share/xcat/netboot/centos/compute.centos-stream8.x86_64.pkglist
  xCAT-server/share/xcat/netboot/centos/compute.centos-stream8.x86_64.postinstall
  xCAT-server/xCAT-server.spec
Labels: component:os_provision

#7032 Make /etc/localtime a link
  xCAT-server/lib/xcat/plugins/packimage.pm
Labels: component:os_provision

#7037 Allow Genesis Builder to run on RHEL8 Systems (2)
  xCAT-genesis-builder/buildrpm
  xCAT-genesis-builder/install
  xCAT-genesis-builder/installkernel
  xCAT-genesis-builder/xcat-cmdline.sh
Labels: component:discovery

#7038 RH8 genesis scripts
  docs/source/references/coral/known_issues/genesis_base.rst
  xCAT-genesis-scripts/usr/bin/doxcat
  xCAT-genesis-scripts/usr/bin/restart
Labels: component:discovery

#7034 compute.ol8.tmpl and compute.rocky.tmpl point to compute.rhels8.tmpl instead of having their own files
  xCAT-server/share/xcat/install/ol/compute.ol8.tmpl
  xCAT-server/share/xcat/install/rh/compute.rhels8.tmpl
  xCAT-server/share/xcat/install/rocky/compute.rocky8.tmpl
Labels: component:os_provision

#7041 Support Fedora34 diskful install
  xCAT-server/lib/xcat/plugins/anaconda.pm
  xCAT-server/share/xcat/install/fedora/compute.fedora34.pkglist
  xCAT-server/share/xcat/install/fedora/compute.fedora34.tmpl
Labels: component:os_provision

#7039 Better xcatprobe message when makedhcp -q returns no output
  xCAT-probe/subcmds/xcatmn
Labels: component:xcatprobe
