Repository xcat2/xcat-core, pull requests merged in 2021-03, with the labels that each got.

#6907 Modify mysqlsetup and restorexCATdb to examine DB restoration delay
  xCAT-client/bin/mysqlsetup
  xCAT-client/sbin/restorexCATdb
Labels: component:database, component:test

#6816 Support OS install on nvme disk
  xCAT-server/share/xcat/install/scripts/getinstdisk
Labels: component:os_provision

#6915 Revert "Modify mysqlsetup and restorexCATdb to examine DB restoration delay"
  xCAT-client/bin/mysqlsetup
  xCAT-client/sbin/restorexCATdb
Labels: component:database, component:test

#6917 Extend XML Simple to pass parser options
  xCAT-server/lib/perl/xCAT/Goconserver.pm
  xCAT-server/lib/perl/xCAT/IPMI.pm
  xCAT-server/lib/perl/xCAT/OPENBMC.pm
  xCAT-server/lib/perl/xCAT/XML.pm
  xCAT-server/sbin/xcatd
Labels: component:xcatd

#6922 Copycds for sles15.2
  xCAT-server/lib/xcat/plugins/sles.pm
Labels: component:os_provision

#6926 Documenation updates for genimage
  docs/source/guides/admin-guides/references/man1/genimage.1.rst
  xCAT-client/pods/man1/genimage.1.pod
Labels: type:documentation

#6927 Use 'find' command to consistently locate vmlinu* file on the disk partition
  xCAT-server/share/xcat/install/scripts/getinstdisk
Labels: component:os_provision

#6924 Add support for SLES15 SP2
  xCAT-server/lib/perl/xCAT/Template.pm
  xCAT-server/share/xcat/install/sles/compute.sle15.pkglist
  xCAT-server/share/xcat/netboot/sles/genimage
Labels: component:os_provision
