Repository xcat2/xcat-core, pull requests merged in 2022-09, with the labels that each got.

#7240 Update xCAT-genesis-base.spec
  xCAT-genesis-builder/xCAT-genesis-base.spec
Labels: component:packaging

#7248 Import/Export image documentation update
  docs/source/guides/admin-guides/manage_clusters/common/deployment/generate_img.rst
Labels: type:documentation

#7244 Update xCAT genesis base build instructions
  xCAT-genesis-builder/README.md
Labels: type:documentation

#7250 Support for diskful Ubuntu20.04 legacy OS image
  xCAT-server/lib/perl/xCAT/SvrUtils.pm
  xCAT-server/lib/xcat/plugins/debian.pm
  xCAT-server/share/xcat/install/ubuntu/compute.tmpl
Labels: component:os_provision

#7252 Support for xCAT installation on Ubuntu20
  build-ubunturepo
  xCAT-server/share/xcat/netboot/ubuntu/compute.ubuntu20.04.x86_64.pkglist
  xCAT/debian/control
  xCATsn/debian/control
Labels: component:os_provision

#7253 Update repository sources for Ubuntu20 testcases
  xCAT-test/autotest/testcase/go_xcat/focal-x86_64.sources.list
Labels: component:test
