Repository xcat2/xcat-core, pull requests merged in 2022-05, with the labels that each got.

#7161 Improve nodeset_shell testcase
  xCAT-test/autotest/testcase/genesis/genesistest.pl
Labels: test:testcase_requested

#7163 SLES15.3 statelite support
  xCAT-server/share/xcat/netboot/add-on/statelite/rc.statelite
  xCAT-server/share/xcat/netboot/sles/dracut_033/xcat-prepivot.sh
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_hierarchy_by_nfs
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_hierarchy_by_ramdisk
Labels: component:os_provision, component:test

#7166 Wait for booted status for nodeshell testcases
  xCAT-test/autotest/testcase/genesis/genesistest.pl
Labels: component:test

#7170 Support xcat-core builds on CentOS8 (2)
  xCAT-SoftLayer/bin/getslnodes.py
  xCAT-SoftLayer/bin/softlayer_storage.py
  xCAT-SoftLayer/xCAT-SoftLayer.spec
  xCAT-probe/scripts/dbstats.py
  xCAT-server/xCAT-server.spec
  xCAT-server/xCAT-wsapi/xcatws-test.py
  xCAT-test/autotest/testcase/xcat_inventory/validatehelper
Labels: component:packaging

#7172 Update docker build containers to CentOS8 (3)
  xCAT-genesis-scripts/xCAT-genesis-scripts.spec
  xCAT-probe/xCAT-probe.spec
  xCAT-server/share/xcat/install/scripts/post.esx
  xCAT-server/share/xcat/install/scripts/post.rh.common
  xCAT-server/share/xcat/install/scripts/post.rhel5.s390x
  xCAT-server/share/xcat/install/scripts/post.rhel6.s390x
  xCAT-server/share/xcat/install/scripts/post.rhels7
  xCAT-server/share/xcat/install/scripts/post.rhels8
  xCAT-server/share/xcat/install/scripts/post.xcat
  xCAT-server/share/xcat/install/scripts/post.xcat.ng
  xCAT-server/share/xcat/install/scripts/pre.pkvm3
  xCAT-vlan/xCAT_plugin/vlan.pm
  xCAT/postscripts/disableconsistentNICrename
  xCAT/postscripts/efibootmgr
  xCAT/postscripts/joindomain
  xCAT/postscripts/serialconsole
  xCAT/postscripts/xcatlib.sh
Labels: component:packaging

#7175 Add perl packages for building on CentOS8 (2)
  xCAT-client/xCAT-client.spec
Labels: component:packaging

#7176 Add perl packages for building on CentOS8 (3)
  xCAT-client/xCAT-client.spec
Labels: component:packaging

#7177 Add perl packages for building on CentOS8 (4)
  xCAT-client/xCAT-client.spec
Labels: component:packaging

#7178 Remove Recommends tag, not supported on CentOS7 build container
  xCAT-client/xCAT-client.spec
Labels: component:packaging

#7180 Better module failure message
  xCAT-server/sbin/xcatd
Labels: component:xcatd

#7168 Fixed error message typo in tabutils.pm
  xCAT-server/lib/xcat/plugins/tabutils.pm
Labels: component:obj_db_cmds, type:usability

#7183 Sync up xcatjktest
  xCAT-server/share/xcat/tools/jenkins/testreport/email.sh
  xCAT-server/share/xcat/tools/jenkins/testreport/send-report.sh
  xCAT-server/share/xcat/tools/jenkins/testreport/xCATjkLogAnalyzer.sql
  xCAT-server/share/xcat/tools/jenkins/testreport/xcatjk-log2sql.sh
  xCAT-server/share/xcat/tools/jenkins/testreport/xcatjk-scanlogs-last3days.sh
  xCAT-server/share/xcat/tools/jenkins/testreport/xcatjk-scanlogs-redo-everything.sh
  xCAT-server/share/xcat/tools/jenkins/testreport/xcatjk-scanlogs.sh
  xCAT-server/share/xcat/tools/jenkins/xcatjktest
Labels: component:test

#7185 Doc update for Service Node upgrading
  docs/source/advanced/hierarchy/provision/diskful_sn.rst
  docs/source/advanced/hierarchy/provision/diskless_sn.rst
  docs/source/advanced/networks/infiniband/mlnxofed_ib_install_preparation.rst
  docs/source/advanced/restapi/restapi_resource/restapi_reference.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/create_img.rst
  docs/source/guides/install-guides/yum/update_xcat.rst
  docs/source/references/coral/known_issues/genesis_base.rst
Labels: type:documentation

#7186 Adding 2.16.4 release information
  docs/source/overview/_files/2.16.x.csv
Labels: type:documentation

#7190 Genesis boot testcase verification
  xCAT-test/autotest/testcase/genesis/genesistest.pl
Labels: component:test

#7189 Update diskinfo of Rocky Linux 8.6
  perl-xCAT/xCAT/data/discinfo.pm
Labels: component:os_provision
