Repository xcat2/xcat-core, pull requests merged in 2022-06, with the labels that each got.

#7192 Update /etc/kdump.conf
  xCAT/postscripts/enablekdump
Labels: component:os_provision

#7194 Merge from master to 2.16 branch for 2.16.4 release. (2)
  perl-xCAT/xCAT/data/discinfo.pm
  xCAT-probe/xcatprobe
  xCAT-test/autotest/testcase/genesis/genesistest.pl
  xCAT-test/autotest/testcase/install_xCAT/case0
  xCAT/postscripts/enablekdump
Labels: component:packaging

#7195 Obtain the highest version of TLS supported by OpenSSL/TLS
  xCAT-test/autotest/testcase/install_xCAT/case0
Labels: component:test

#7197 Better file linking for xCAT-probe
  xCAT-probe/debian/xcat-probe.links
  xCAT-probe/xCAT-probe.spec
  xCAT-probe/xcatprobe
Labels: component:xcatprobe

#7199 Merge from master to 2.16 branch for 2.16.4 release. (3)
  xCAT-probe/debian/xcat-probe.links
  xCAT-probe/xCAT-probe.spec
  xCAT-probe/xcatprobe
  xCAT-test/autotest/testcase/install_xCAT/case0
Labels: component:packaging

#7200 Adding 2.16.4 release information(2)
  docs/source/overview/_files/2.16.x.csv
Labels: type:documentation

#7201 Update version number
  docs/source/conf.py
Labels: type:documentation

#7202 Improve PR 7193: Check host keys supported by the operating system and report new ones if any
  xCAT-test/autotest/testcase/install_xCAT/case0
Labels: component:test

#7205 Improve SLES15 copycds for Media2 iso
  xCAT-server/lib/xcat/plugins/sles.pm
Labels: component:os_provision

#7206 Trigger github action to rebuild xCAT
  .github/workflows/xcat_test.yml
Labels: component:automation

#7207 Fix indentation in GitHub action to rebuild xCAT
  .github/workflows/xcat_test.yml
Labels: component:automation

#7211 More debuggin in GitHub actions script
  github_action_xcat_test.pl
Labels: component:automation

#7213 Get GitHub action script directory reference3
  github_action_xcat_test.pl
Labels: component:automation
