Repository xcat2/xcat-core, pull requests merged in 2022-01, with the labels that each got.

#7083 Use specified non-root user for REST API nodeshell method
  xCAT-server/lib/xcat/plugins/xdsh.pm
Labels: component:restapi

#7080 Do not write the pid of chronyd to /dev/null for all distros
  xCAT/postscripts/setupntp
Labels: component:postscripts

#7084 Add testcases for nodeshell REST API method
  xCAT-test/autotest/bundle/restapi.bundle
  xCAT-test/autotest/testcase/restapi/cases0
Labels: component:restapi, component:test

#7085 Add RHEL8 IB pkglist files
  xCAT-server/share/xcat/ib/netboot/rh/ib.rhels8.ppc64le.pkglist
  xCAT-server/share/xcat/ib/netboot/rh/ib.rhels8.x86_64.pkglist
Labels: component:infiniband, component:os_provision

#7087 Disable internet repos to avoid unexpected and silent upgrades
  xCAT-server/share/xcat/install/scripts/post.rhels8
  xCAT-server/share/xcat/netboot/rh/genimage
Labels: component:os_provision

#7088 Add testcase for nodeshell REST API method for non-root user(2)
  xCAT-test/autotest/testcase/restapi/cases0
Labels: component:restapi, component:test

#7089 Add testcase for nodeshell REST API method for non-root user(3)
  xCAT-test/autotest/testcase/restapi/cases0
Labels: component:restapi, component:test

#7073 Update pasu command documentation
  docs/source/guides/admin-guides/references/man1/pasu.1.rst
  xCAT-client/pods/man1/pasu.1.pod
Labels: type:documentation

#7090 Add testcase for nodeshell REST API method for non-root user(4)
  xCAT-test/autotest/testcase/restapi/cases0
Labels: component:restapi, component:test

#7094 Delay userdel by 11 seconds in xdcp_nonroot_user for RHEL 8.5
  xCAT-test/autotest/testcase/xdcp/cases1
Labels: component:test

#6975 Add initial support for deploying Ubuntu 20.04 nodes.
  xCAT-server/lib/perl/xCAT/SvrUtils.pm
  xCAT-server/lib/xcat/plugins/debian.pm
  xCAT-server/share/xcat/install/scripts/getinstdisk
  xCAT-server/share/xcat/install/scripts/pre.ubuntu.subiquity
  xCAT-server/share/xcat/install/ubuntu/compute.subiquity.tmpl
  xCAT-server/share/xcat/install/ubuntu/compute.ubuntu20.04.x86_64.pkglist
Labels: component:os_provision

#7095 Fix OpenPOWER detection regex
  xCAT-server/lib/xcat/plugins/ipmi.pm
Labels: component:hw_control

#7099 Update SLES15 compute template
  xCAT-server/lib/perl/xCAT/Template.pm
  xCAT-server/share/xcat/install/sles/compute.sle15.tmpl
Labels: component:os_provision
