Repository xcat2/xcat-core, pull requests merged in 2022-07, with the labels that each got.

#7215 Testecase to detect genimage WARNING
  xCAT-test/autotest/testcase/xdsh/cases0
Labels: component:test

#7216 Test pull_request action instead of push
  .github/workflows/xcat_test.yml
Labels: component:automation

#7179 Fix warnings of newer dracut versions
  xCAT-server/share/xcat/netboot/rh/genimage
  xCAT-server/share/xcat/netboot/sles/genimage
  xCAT-server/share/xcat/netboot/ubuntu/genimage
Labels: component:os_provision

#7217 Fix mkvm man page formatting
  docs/source/guides/admin-guides/references/man1/mkvm.1.rst
  github_action_xcat_test.pl
  xCAT-client/pods/man1/mkvm.1.pod
  xCAT-test/xcattest
Labels: type:documentation

#7219 Fix rmvm man page formatting
  docs/source/guides/admin-guides/references/man1/rmvm.1.rst
  xCAT-client/pods/man1/rmvm.1.pod
Labels: type:documentation
