Repository xcat2/xcat-core, pull requests merged in 2022-02, with the labels that each got.

#7077 Improve packimage time zone handling
  xCAT-server/lib/xcat/plugins/packimage.pm
Labels: component:os_provision

#7101 Updates to mkvm, chvm, and lsvm documentation.
  docs/source/guides/admin-guides/references/man1/chvm.1.rst
  docs/source/guides/admin-guides/references/man1/lsvm.1.rst
  docs/source/guides/admin-guides/references/man1/mkvm.1.rst
  xCAT-client/pods/man1/chvm.1.pod
  xCAT-client/pods/man1/lsvm.1.pod
  xCAT-client/pods/man1/mkvm.1.pod
Labels: type:documentation, component:virtualization

#7100 Fix typos on help output for genimage and OpenStack
  xCAT-OpenStack/postscripts/setup_openstack_repo
  xCAT-client/bin/genimage
Labels: type:documentation

#7102 Spelling corrections for man pages
  docs/source/guides/admin-guides/references/man1/addkit.1.rst
  docs/source/guides/admin-guides/references/man1/addkitcomp.1.rst
  docs/source/guides/admin-guides/references/man1/chhypervisor.1.rst
  docs/source/guides/admin-guides/references/man1/chvm.1.rst
  docs/source/guides/admin-guides/references/man1/imgcapture.1.rst
  docs/source/guides/admin-guides/references/man1/imgexport.1.rst
  docs/source/guides/admin-guides/references/man1/lskit.1.rst
  docs/source/guides/admin-guides/references/man1/makentp.1.rst
  docs/source/guides/admin-guides/references/man1/mknimimage.1.rst
  docs/source/guides/admin-guides/references/man1/mkvm.1.rst
  docs/source/guides/admin-guides/references/man1/monstart.1.rst
  docs/source/guides/admin-guides/references/man1/monstop.1.rst
  docs/source/guides/admin-guides/references/man1/pcons.1.rst
  docs/source/guides/admin-guides/references/man1/renergy.1.rst
  docs/source/guides/admin-guides/references/man1/rflash.1.rst
  docs/source/guides/admin-guides/references/man1/rmkitcomp.1.rst
  docs/source/guides/admin-guides/references/man1/rmnimimage.1.rst
  docs/source/guides/admin-guides/references/man1/rnetboot.1.rst
  docs/source/guides/admin-guides/references/man1/rscan.1.rst
  docs/source/guides/admin-guides/references/man1/rspconfig.1.rst
  docs/source/guides/admin-guides/references/man1/sinv.1.rst
  docs/source/guides/admin-guides/references/man1/snmove.1.rst
  docs/source/guides/admin-guides/references/man1/switchdiscover.1.rst
  docs/source/guides/admin-guides/references/man1/unregnotif.1.rst
  docs/source/guides/admin-guides/references/man1/xcatchroot.1.rst
  docs/source/guides/admin-guides/references/man1/xdsh.1.rst
  docs/source/guides/admin-guides/references/man3/noderange.3.rst
  xCAT-client/pods/man1/addkit.1.pod
  xCAT-client/pods/man1/addkitcomp.1.pod
  xCAT-client/pods/man1/chhypervisor.1.pod
  xCAT-client/pods/man1/chvm.1.pod
  xCAT-client/pods/man1/imgcapture.1.pod
  xCAT-client/pods/man1/imgexport.1.pod
  xCAT-client/pods/man1/lskit.1.pod
  xCAT-client/pods/man1/makentp.1.pod
  xCAT-client/pods/man1/mknimimage.1.pod
  xCAT-client/pods/man1/mkvm.1.pod
  xCAT-client/pods/man1/monstart.1.pod
  xCAT-client/pods/man1/monstop.1.pod
  xCAT-client/pods/man1/pcons.1.pod
  xCAT-client/pods/man1/renergy.1.pod
  xCAT-client/pods/man1/rflash.1.pod
  xCAT-client/pods/man1/rmkitcomp.1.pod
  xCAT-client/pods/man1/rmnimimage.1.pod
  xCAT-client/pods/man1/rnetboot.1.pod
  xCAT-client/pods/man1/rscan.1.pod
  xCAT-client/pods/man1/rspconfig.1.pod
  xCAT-client/pods/man1/sinv.1.pod
  xCAT-client/pods/man1/snmove.1.pod
  xCAT-client/pods/man1/switchdiscover.1.pod
  xCAT-client/pods/man1/unregnotif.1.pod
  xCAT-client/pods/man1/xcatchroot.1.pod
  xCAT-client/pods/man1/xdsh.1.pod
  xCAT-client/pods/man3/noderange.3.pod
Labels: type:documentation

#7104 Update SLES15 service and compute template
  xCAT-server/share/xcat/install/sles/compute.sle15.tmpl
  xCAT-server/share/xcat/install/sles/service.sle15.pkglist
  xCAT-server/share/xcat/install/sles/service.sle15.tmpl
  xCAT-test/autotest/testcase/installation/reg_linux_diskfull_installation_flat
  xCAT-test/autotest/testcase/installation/reg_linux_diskfull_installation_hierarchy
Labels: component:os_provision, component:test

#7107 Handle SLES15 persistent kcmdline attribute (2)
  docs/source/guides/admin-guides/references/man5/bootparams.5.rst
  docs/source/guides/admin-guides/references/man7/group.7.rst
  docs/source/guides/admin-guides/references/man7/node.7.rst
  perl-xCAT/xCAT/Schema.pm
  xCAT-server/share/xcat/install/sles/compute.sle15.tmpl
  xCAT-server/share/xcat/install/sles/service.sle15.tmpl
Labels: type:documentation, component:os_provision

#7108 Finished spelling corrections for current documenation
  docs/source/advanced/chain/create_image_for_runimage.rst
  docs/source/advanced/docker/dockerized_xcat/run_xcat_in_docker_host.rst
  docs/source/advanced/hamn/setup_ha_mgmt_node_with_shared_data.rst
  docs/source/advanced/kit/custom/build/createkit.rst
  docs/source/advanced/kit/custom/build/kitrepo.rst
  docs/source/advanced/kit/custom/introduction.rst
  docs/source/advanced/migration/migration.rst
  docs/source/advanced/networks/ethernet_switches/ethernet_switches.rst
  docs/source/advanced/networks/infiniband/mlnxofed_ib_install_diskless.rst
  docs/source/advanced/networks/infiniband/mlnxofed_ib_install_preparation.rst
  docs/source/advanced/networks/infiniband/ufm_configuration.rst
  docs/source/advanced/networks/onie_switches/index.rst
  docs/source/advanced/networks/onie_switches/os_cumulus/manage.rst
  docs/source/advanced/networks/onie_switches/os_cumulus/prepare.rst
  docs/source/advanced/networks/onie_switches/os_cumulus/ztp.rst
  docs/source/advanced/networks/switchdiscover/switch_based_switch_discovery.rst
  docs/source/advanced/networks/switchdiscover/switches_discovery.rst
  docs/source/advanced/pdu/index.rst
  docs/source/advanced/performance_tuning/index.rst
  docs/source/advanced/performance_tuning/linux_os_tuning.rst
  docs/source/advanced/probe/osdeploy.rst
  docs/source/advanced/restapi/restapi_resource/restapi_reference.rst
  docs/source/advanced/restapi/restapi_setup/restapi_setup.rst
  docs/source/advanced/security/ssl_config.rst
  docs/source/advanced/xcat-inventory/define_create_cluster.rst
  docs/source/advanced/xcat-inventory/index.rst
  docs/source/advanced/xcat-inventory/version_control_inventory.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/additionalpkg/nonubuntu_os_pkg.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/create_img.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/driver_update_disk.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/network/cfg_network_bridge.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/network/cfg_network_vlan.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/prepostscripts/postinstall_script.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/syncfile/syncfile_synclist_file.rst
  docs/source/guides/admin-guides/manage_clusters/common/deployment/syncfile/syncfile_xdcp.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/discovery/mtms/discovery_using_defined.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/discovery/mtms/discovery_using_dhcp.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/discovery/seq_discovery.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/discovery/switch_discovery.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/network/cfg_network_adapter.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/network/cfg_network_adapter.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/statelite/index.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/statelite/provision_statelite.rst
  docs/source/guides/admin-guides/manage_clusters/ppc64le/virtual_machines/FAQ.rst
  docs/source/references/coral/cluster_mgmt/scalability/python/install/index.rst
  docs/source/references/coral/ha/ha_mgmt_node_with_shared_data.rst
  docs/source/references/coral/index.rst
  docs/source/security/2016/20160115_openssl.rst
  docs/source/security/2017/20171212_tls.rst
  docs/source/troubleshooting/index.rst
Labels: type:documentation

#7111 Testcase improvement for diskless_kdump
  xCAT-test/autotest/testcase/kdump/linux_diskless_kdump
Labels: component:test

#7112 Add a crashkernel size check to linux_diskless_kdump testcase
  xCAT-test/autotest/testcase/kdump/linux_diskless_kdump
Labels: component:test

#7113 Modify docs to describe how to add extra drivers/modules for discovery
  docs/source/guides/admin-guides/manage_clusters/ppc64le/discovery/index.rst
  docs/source/references/coral/known_issues/genesis_base.rst
Labels: type:documentation, component:discovery

#7114 Fixed makedns autotest tescases
  xCAT-test/autotest/testcase/makedns/cases0
Labels: type:bug, component:dns, component:test

#7115 Improve readability of generated AutoYaST for SLES15
  xCAT-server/lib/perl/xCAT/Template.pm
Labels: component:os_provision

#7116 Add packages missing from default SLES15 SP3 installation
  xCAT-server/share/xcat/install/sles/compute.sle15.pkglist
Labels: component:os_provision

#7117 Modified autotest makedns testcase to match old and new nslookup output
  xCAT-test/autotest/testcase/makedns/cases0
Labels: component:test, component:CI
