Repository xcat2/xcat-core, pull requests merged in 2023-02, with the labels that each got.

#7325 Fix password testcases for sha512
  xCAT-test/autotest/testcase/passwd/case0
Labels: component:test

#7324 Add Perl library path to xcat.sh
  xCAT-client/xCAT-client.spec
Labels: component:packaging

#7326 Add Perl library path to xcat.csh
  xCAT-client/xCAT-client.spec
Labels: component:packaging

#7327 Update github action to run on Ubuntu20
  .github/workflows/xcat_test.yml
Labels: component:test, component:automation

#7331 Update testcases to run on AlmaLinux
  xCAT-test/autotest/testcase/installation/SN_setup_case
  xCAT-test/autotest/testcase/restapi/cases0
Labels: component:test

#7333 Additional testcase changes for AlmaLinux
  xCAT-test/autotest/testcase/installation/SN_setup_case
  xCAT-test/autotest/testcase/installation/reg_linux_diskless_installation_hierarchy
  xCAT-test/autotest/testcase/passwd/case0
Labels: component:test

#7334 Additional testcase and postscript changes for AlmaLinux
  xCAT-test/autotest/testcase/confignetwork/cases0
  xCAT-test/autotest/testcase/installation/reg_linux_diskless_installation_hierarchy
  xCAT/postscripts/ospkgs
  xCAT/postscripts/otherpkgs
Labels: component:postscripts, component:test

#7335 Fix mysql setup for RH family of OSes
  xCAT-client/bin/mysqlsetup
Labels: component:database

#7328 Fix EL9 chroot detection for syncfiles
  xCAT/postscripts/xcatlib.sh
Labels: component:postscripts

#7336 More testcase changes for AlmaLinux
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_hierarchy_by_nfs
  xCAT-test/autotest/testcase/installation/reg_linux_statelite_installation_hierarchy_by_ramdisk
Labels: component:test

#7338 Fix syntax error in pgsqlsetup
  xCAT-client/bin/pgsqlsetup
Labels: component:database

#7337 mysqlsetup enhancements
  docs/source/advanced/hierarchy/databases/mysql_remove.rst
  docs/source/advanced/hierarchy/databases/postgres_remove.rst
  docs/source/guides/admin-guides/references/man1/mysqlsetup.1.rst
  docs/source/guides/admin-guides/references/man5/nodetype.5.rst
  docs/source/guides/admin-guides/references/man5/osimage.5.rst
  docs/source/guides/admin-guides/references/man5/passwd.5.rst
  docs/source/guides/admin-guides/references/man7/group.7.rst
  docs/source/guides/admin-guides/references/man7/node.7.rst
  docs/source/guides/admin-guides/references/man7/osimage.7.rst
  xCAT-client/bin/mysqlsetup
  xCAT-client/pods/man1/mysqlsetup.1.pod
Labels: component:database

#7339 Fixed comments in sudoer postscript for issue #7301
  xCAT/postscripts/sudoer
Labels: component:postscripts

#7256 Add ipmi_si module to be able to run bmcsetup manually
  xCAT-genesis-scripts/usr/bin/bmcsetup
Labels: component:postscripts

#7295 Remove deprecated blocksize argument
  xCAT-server/lib/perl/xCAT/IPMI.pm
Labels: component:hw_control

#7344 SLES15.4 genimage dracut rpm version
  xCAT-server/share/xcat/netboot/sles/genimage
Labels: component:os_provision

#7345 Update xcat_test.yml
  .github/workflows/xcat_test.yml
Labels: component:CI

#7348 Fix RHEL9 yum repo paths for ospkgs and otherpkgs
  xCAT/postscripts/ospkgs
  xCAT/postscripts/otherpkgs
Labels: component:os_provision

#7347 Clean up build warnings on RHEL
  xCAT-genesis-scripts/usr/bin/bmcsetup
  xCAT/postscripts/setupesx
  xCAT/postscripts/xcatpostinit.service
Labels: component:packaging
