Repository xcat2/xcat-core, pull requests merged in 2023-03, with the labels that each got.

#7349 Fix bind version comparison
  xCAT-server/sbin/makenamed.conf
Labels: component:dns

#7350 Dummy pod files need content
  xCAT-client/xpod2man
Labels: component:packaging

#7352 Adding 2.16.5 release information
  docs/source/overview/_files/2.16.x.csv
Labels: type:documentation

#7353 go-xcat should not use available option
  xCAT-server/share/xcat/tools/go-xcat
Labels: component:go-xcat

#7354 Fixed typo in readthedocs SSL config page
  docs/source/advanced/security/ssl_config.rst
Labels: type:documentation

#7357 Added security advisory documentation for xCAT CVE-2023-27486
  docs/source/security/2023/20230308_xcat.rst
  docs/source/security/2023/index.rst
  docs/source/security/index.rst
Labels: component:security

#7358 Improve imgexport man page description of destination parameter
  docs/source/guides/admin-guides/references/man1/imgexport.1.rst
  docs/source/guides/admin-guides/references/man1/imgimport.1.rst
  xCAT-client/pods/man1/imgexport.1.pod
  xCAT-client/pods/man1/imgimport.1.pod
Labels: type:documentation

#7359 Added Eclipse Public License 1.0 LICENSE file
  LICENSE
Labels: type:documentation

#7363 Move SLES12 Postgres package from pkglist to otherpkglist
  xCAT-server/share/xcat/install/sles/service.sles12.pkglist
  xCAT-server/share/xcat/install/sles/service.sles12.ppc64le.otherpkgs.pkglist
  xCAT-server/share/xcat/install/sles/service.sles12.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/sles/service.sles12.pkglist
  xCAT-server/share/xcat/netboot/sles/service.sles12.ppc64le.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/sles/service.sles12.x86_64.otherpkgs.pkglist
Labels: component:hierarchy, component:os_provision

#7364 Add restapi testcase to reset attribute
  xCAT-test/autotest/bundle/restapi.bundle
  xCAT-test/autotest/testcase/restapi/cases0
Labels: component:restapi, component:test, test:testcase_added

#7367 Handle RESTAPI parameters with null values
  xCAT-server/xCAT-wsapi/xcatws.cgi
Labels: component:restapi

#7368 Reduce the VNC password from 20 characters to 8
  xCAT-server/lib/xcat/plugins/kvm.pm
Labels: component:virtualization
