Repository xcat2/xcat-core, pull requests merged in 2024-02, with the labels that each got.

#7423 Fix and improve readthedocs docu
  .readthedocs.yaml
  docs/README.md
  docs/requirements.txt
  docs/source/conf.py
Labels: type:documentation

#7420 Add more disk infos for copycds
  perl-xCAT/xCAT/data/discinfo.pm
Labels: component:os_provision, rh9

#7418 Allow IPoIB MAC addresses for provisioning via IPoIB
  xCAT-server/lib/xcat/plugins/dhcp.pm
Labels: component:dhcp, component:infiniband, component:os_provision

#6876 [doc only] Add vlan to networks documentation
  docs/source/advanced/networks/index.rst
Labels: type:documentation

#7386 Add workaround for deprecated old commands in sles-15 into go-xcat
  xCAT-server/share/xcat/tools/go-xcat
Labels: component:go-xcat

#6391 Implement HMAC-SHA256 in xCAT IPMI
  xCAT-server/lib/perl/xCAT/IPMI.pm
Labels: component:hw_control, component:security

#7419 Add osimage symlinks for EL9 distros
  xCAT-server/share/xcat/install/alma/compute.alma9.pkglist
  xCAT-server/share/xcat/install/alma/compute.alma9.tmpl
  xCAT-server/share/xcat/install/alma/service.alma9.pkglist
  xCAT-server/share/xcat/install/alma/service.alma9.tmpl
  xCAT-server/share/xcat/install/alma/service.alma9.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/install/ol/compute.ol9.pkglist
  xCAT-server/share/xcat/install/ol/compute.ol9.tmpl
  xCAT-server/share/xcat/install/ol/service.ol9.pkglist
  xCAT-server/share/xcat/install/ol/service.ol9.tmpl
  xCAT-server/share/xcat/install/ol/service.ol9.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/install/rocky/compute.rocky9.pkglist
  xCAT-server/share/xcat/install/rocky/compute.rocky9.tmpl
  xCAT-server/share/xcat/install/rocky/service.rocky9.pkglist
  xCAT-server/share/xcat/install/rocky/service.rocky9.tmpl
  xCAT-server/share/xcat/install/rocky/service.rocky9.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/alma/compute.alma9.x86_64.exlist
  xCAT-server/share/xcat/netboot/alma/compute.alma9.x86_64.pkglist
  xCAT-server/share/xcat/netboot/alma/compute.alma9.x86_64.postinstall
  xCAT-server/share/xcat/netboot/alma/service.alma9.x86_64.exlist
  xCAT-server/share/xcat/netboot/alma/service.alma9.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/alma/service.alma9.x86_64.pkglist
  xCAT-server/share/xcat/netboot/alma/service.alma9.x86_64.postinstall
  xCAT-server/share/xcat/netboot/ol/compute.ol9.x86_64.exlist
  xCAT-server/share/xcat/netboot/ol/compute.ol9.x86_64.pkglist
  xCAT-server/share/xcat/netboot/ol/compute.ol9.x86_64.postinstall
  xCAT-server/share/xcat/netboot/ol/service.ol9.x86_64.exlist
  xCAT-server/share/xcat/netboot/ol/service.ol9.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/ol/service.ol9.x86_64.pkglist
  xCAT-server/share/xcat/netboot/ol/service.ol9.x86_64.postinstall
  xCAT-server/share/xcat/netboot/rocky/compute.rocky9.x86_64.exlist
  xCAT-server/share/xcat/netboot/rocky/compute.rocky9.x86_64.pkglist
  xCAT-server/share/xcat/netboot/rocky/compute.rocky9.x86_64.postinstall
  xCAT-server/share/xcat/netboot/rocky/service.rocky9.x86_64.exlist
  xCAT-server/share/xcat/netboot/rocky/service.rocky9.x86_64.otherpkgs.pkglist
  xCAT-server/share/xcat/netboot/rocky/service.rocky9.x86_64.pkglist
  xCAT-server/share/xcat/netboot/rocky/service.rocky9.x86_64.postinstall
Labels: component:os_provision, rh9

#7417 Fix dracut warnings during genimage on newer OSs
  xCAT-server/share/xcat/netboot/rh/genimage
Labels: component:os_provision, rh9

#7427 Do not check certificate when getting repomd.xml.key
  buildcore.sh
Labels: component:packaging

#7426 Add support for non-zero LUN
  xCAT-server/lib/perl/xCAT/IPMI.pm
  xCAT-server/lib/xcat/plugins/ipmi.pm
Labels: component:hw_control
