Repository xcat2/xcat-core, pull requests merged in 2024-06, with the labels that each got.

#7440 EL9: Adding parsing NM resolv.conf for dns entries
  xCAT/postscripts/configeth
Labels: type:bug, rh9

#7447 Add support for static IPv6 addresses for EL9
  xCAT/postscripts/configeth
Labels: rh9

#7444 Use 'nmcli con modify' for nicextraparams on RHEL9
  xCAT/postscripts/configeth
  xCAT/postscripts/configib
  xCAT/postscripts/nicutils.sh
Labels: type:bug, rh9

#6989 Fix hack_uname() of mlnxofed_ib_install: POSIX compliance
  xCAT-server/share/xcat/ib/scripts/Mellanox/mlnxofed_ib_install
Labels: component:infiniband
